/*
 * Internal module API header file.
 *
 * Generated by SIP 4.19.7
 */

#ifndef _SafetAPI_H
#define _SafetAPI_H

#include <sip.h>

#include <QMetaType>
#include <QThread>

/* These are the qualifiers that are enabled. */
#define SIP_FEATURE_PyQt_Process
#define SIP_FEATURE_PyQt_NotBootstrapped
#define SIP_FEATURE_PyQt_Deprecated_5_0
#define SIP_FEATURE_PyQt_NoOpenGLES
#define SIP_FEATURE_PyQt_RawFont
#define SIP_FEATURE_PyQt_SystemTrayIcon
#define SIP_FEATURE_PyQt_PrintPreviewDialog
#define SIP_FEATURE_PyQt_PrintPreviewWidget
#define SIP_FEATURE_PyQt_Printer
#define SIP_FEATURE_PyQt_PrintDialog
#define SIP_FEATURE_Py_v3
#define SIP_FEATURE_PyQt_qreal_double
#define SIP_FEATURE_PyQt_SizeGrip
#define SIP_FEATURE_PyQt_OpenSSL
#define SIP_FEATURE_Py_DateTime
#define SIP_FEATURE_PyQt_NoQtPrintRangeBug
#define SIP_FEATURE_PyQt_WhatsThis
#define SIP_FEATURE_PyQt_ToolTip
#define SIP_FEATURE_PyQt_StatusTip
#define SIP_FEATURE_PyQt_SessionManager
#define SIP_FEATURE_PyQt_Accessibility
#define SIP_PLATFORM_WS_X11
#define SIP_TIMELINE_Qt_4_8_6


/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_numberOfSignaturesOnOpenXAdESContainer 0
#define sipName_numberOfSignaturesOnOpenXAdESContainer &sipStrings_Safet[0]
#define sipNameNr_numberOfDataFileOnOpenXAdESContainer 39
#define sipName_numberOfDataFileOnOpenXAdESContainer &sipStrings_Safet[39]
#define sipNameNr_addSignatureToExistingDigidocFile 76
#define sipName_addSignatureToExistingDigidocFile &sipStrings_Safet[76]
#define sipNameNr_SafetDocument__SignatureOperator 110
#define sipName_SafetDocument__SignatureOperator &sipStrings_Safet[110]
#define sipNameNr_getSignerCertificateIssuerName 143
#define sipName_getSignerCertificateIssuerName &sipStrings_Safet[143]
#define sipNameNr_getCommonNameFromCertificate 174
#define sipName_getCommonNameFromCertificate &sipStrings_Safet[174]
#define sipNameNr_PyQt4_QtCore_pyqtWrapperType 203
#define sipName_PyQt4_QtCore_pyqtWrapperType &sipStrings_Safet[203]
#define sipNameNr_SafetWorkflow__OutputFormat 232
#define sipName_SafetWorkflow__OutputFormat &sipStrings_Safet[232]
#define sipNameNr_verifySignMadeWithSmartCard 260
#define sipName_verifySignMadeWithSmartCard &sipStrings_Safet[260]
#define sipNameNr_getSignerCertificateSerial 288
#define sipName_getSignerCertificateSerial &sipStrings_Safet[288]
#define sipNameNr_numberOfDataFileAttributes 315
#define sipName_numberOfDataFileAttributes &sipStrings_Safet[315]
#define sipNameNr_getPostalCodeOfSignature 342
#define sipName_getPostalCodeOfSignature &sipStrings_Safet[342]
#define sipNameNr_signWithPrivateKeyOnFile 367
#define sipName_signWithPrivateKeyOnFile &sipStrings_Safet[367]
#define sipNameNr_verifyDocumentsFromData 392
#define sipName_verifyDocumentsFromData &sipStrings_Safet[392]
#define sipNameNr_createXMLFileFromQuery 416
#define sipName_createXMLFileFromQuery &sipStrings_Safet[416]
#define sipNameNr_authorityKeyIdentifier 439
#define sipName_authorityKeyIdentifier &sipStrings_Safet[439]
#define sipNameNr_setPathOfSafetDocument 462
#define sipName_setPathOfSafetDocument &sipStrings_Safet[462]
#define sipNameNr_getPathOfSafetDocument 485
#define sipName_getPathOfSafetDocument &sipStrings_Safet[485]
#define sipNameNr_getSingingTimeOnlyHour 508
#define sipName_getSingingTimeOnlyHour &sipStrings_Safet[508]
#define sipNameNr_getSingingTimeOnlyDate 531
#define sipName_getSingingTimeOnlyDate &sipStrings_Safet[531]
#define sipNameNr_getNumberOfPrivateKeys 554
#define sipName_getNumberOfPrivateKeys &sipStrings_Safet[554]
#define sipNameNr_getCommonNameOfSigners 577
#define sipName_getCommonNameOfSigners &sipStrings_Safet[577]
#define sipNameNr_initDigidocConfigStore 600
#define sipName_initDigidocConfigStore &sipStrings_Safet[600]
#define sipNameNr_623 623
#define sipName_623 &sipStrings_Safet[623]
#define sipNameNr_645 645
#define sipName_645 &sipStrings_Safet[645]
#define sipNameNr_signDocumentsFromData 667
#define sipName_signDocumentsFromData &sipStrings_Safet[667]
#define sipNameNr_getPublicKeyAlgorithm 689
#define sipName_getPublicKeyAlgorithm &sipStrings_Safet[689]
#define sipNameNr_getCountryOfSignature 711
#define sipName_getCountryOfSignature &sipStrings_Safet[711]
#define sipNameNr_getDataBaseTableNames 733
#define sipName_getDataBaseTableNames &sipStrings_Safet[733]
#define sipNameNr_changeConnXMLWorkflow 755
#define sipName_changeConnXMLWorkflow &sipStrings_Safet[755]
#define sipNameNr_subjectKeyIdentifier 777
#define sipName_subjectKeyIdentifier &sipStrings_Safet[777]
#define sipNameNr_createXMLFileFromSQL 798
#define sipName_createXMLFileFromSQL &sipStrings_Safet[798]
#define sipNameNr_delNodeToXMLWorkflow 819
#define sipName_delNodeToXMLWorkflow &sipStrings_Safet[819]
#define sipNameNr_addNodeToXMLWorkflow 840
#define sipName_addNodeToXMLWorkflow &sipStrings_Safet[840]
#define sipNameNr_addInfoGraphDateText 861
#define sipName_addInfoGraphDateText &sipStrings_Safet[861]
#define sipNameNr_convertXMLtoObjects 882
#define sipName_convertXMLtoObjects &sipStrings_Safet[882]
#define sipNameNr_getStateOfSignature 902
#define sipName_getStateOfSignature &sipStrings_Safet[902]
#define sipNameNr_testSmartCardDriver 922
#define sipName_testSmartCardDriver &sipStrings_Safet[922]
#define sipNameNr_getDataFileMimeType 942
#define sipName_getDataFileMimeType &sipStrings_Safet[942]
#define sipNameNr_doSaveConfiguration 962
#define sipName_doSaveConfiguration &sipStrings_Safet[962]
#define sipNameNr_doLoadConfiguration 982
#define sipName_doLoadConfiguration &sipStrings_Safet[982]
#define sipNameNr_defaultButtonNumber 1002
#define sipName_defaultButtonNumber &sipStrings_Safet[1002]
#define sipNameNr_getPublicKeyLength 1022
#define sipName_getPublicKeyLength &sipStrings_Safet[1022]
#define sipNameNr_getSignatureFormat 1041
#define sipName_getSignatureFormat &sipStrings_Safet[1041]
#define sipNameNr_signatureLocations 1060
#define sipName_signatureLocations &sipStrings_Safet[1060]
#define sipNameNr_getCityOfSignature 1079
#define sipName_getCityOfSignature &sipStrings_Safet[1079]
#define sipNameNr_returnFileToString 1098
#define sipName_returnFileToString &sipStrings_Safet[1098]
#define sipNameNr_checkAndExecEvents 1117
#define sipName_checkAndExecEvents &sipStrings_Safet[1117]
#define sipNameNr_doPermiseOperation 1136
#define sipName_doPermiseOperation &sipStrings_Safet[1136]
#define sipNameNr_loadReportTemplate 1155
#define sipName_loadReportTemplate &sipStrings_Safet[1155]
#define sipNameNr_generateModifyHTML 1174
#define sipName_generateModifyHTML &sipStrings_Safet[1174]
#define sipNameNr_generateFormFooter 1193
#define sipName_generateFormFooter &sipStrings_Safet[1193]
#define sipNameNr_escapeButtonNumber 1212
#define sipName_escapeButtonNumber &sipStrings_Safet[1212]
#define sipNameNr_setDocumentsource 1231
#define sipName_setDocumentsource &sipStrings_Safet[1231]
#define sipNameNr_signatureLocation 1249
#define sipName_signatureLocation &sipStrings_Safet[1249]
#define sipNameNr_SignatureOperator 125
#define sipName_SignatureOperator &sipStrings_Safet[125]
#define sipNameNr_connectToDataBase 1267
#define sipName_connectToDataBase &sipStrings_Safet[1267]
#define sipNameNr_getDataFileLength 1285
#define sipName_getDataFileLength &sipStrings_Safet[1285]
#define sipNameNr_checkUserRegister 1303
#define sipName_checkUserRegister &sipStrings_Safet[1303]
#define sipNameNr_currentGraphTitle 1321
#define sipName_currentGraphTitle &sipStrings_Safet[1321]
#define sipNameNr_setConffileValues 1339
#define sipName_setConffileValues &sipStrings_Safet[1339]
#define sipNameNr_getFlowParameters 1357
#define sipName_getFlowParameters &sipStrings_Safet[1357]
#define sipNameNr_destroySubWindows 1375
#define sipName_destroySubWindows &sipStrings_Safet[1375]
#define sipNameNr_senderSignalIndex 1393
#define sipName_senderSignalIndex &sipStrings_Safet[1393]
#define sipNameNr_loadAllConfFiles 1411
#define sipName_loadAllConfFiles &sipStrings_Safet[1411]
#define sipNameNr_getDocumentCount 1428
#define sipName_getDocumentCount &sipStrings_Safet[1428]
#define sipNameNr_enhancedKeyUsage 1445
#define sipName_enhancedKeyUsage &sipStrings_Safet[1445]
#define sipNameNr_getSignatureType 1462
#define sipName_getSignatureType &sipStrings_Safet[1462]
#define sipNameNr_getTempNameFiles 1479
#define sipName_getTempNameFiles &sipStrings_Safet[1479]
#define sipNameNr_generateFormHead 1496
#define sipName_generateFormHead &sipStrings_Safet[1496]
#define sipNameNr_setHostMediaPath 1513
#define sipName_setHostMediaPath &sipStrings_Safet[1513]
#define sipNameNr_destroyOldWindow 1530
#define sipName_destroyOldWindow &sipStrings_Safet[1530]
#define sipNameNr_initializeWindow 1547
#define sipName_initializeWindow &sipStrings_Safet[1547]
#define sipNameNr_disconnectNotify 1564
#define sipName_disconnectNotify &sipStrings_Safet[1564]
#define sipNameNr_ParsedSqlToData 1581
#define sipName_ParsedSqlToData &sipStrings_Safet[1581]
#define sipNameNr_openDataSources 1597
#define sipName_openDataSources &sipStrings_Safet[1597]
#define sipNameNr_writeX509ToFile 1613
#define sipName_writeX509ToFile &sipStrings_Safet[1613]
#define sipNameNr_subjectInfoUtf8 1629
#define sipName_subjectInfoUtf8 &sipStrings_Safet[1629]
#define sipNameNr_getCountOfRoles 1645
#define sipName_getCountOfRoles &sipStrings_Safet[1645]
#define sipNameNr_decryptDocument 1661
#define sipName_decryptDocument &sipStrings_Safet[1661]
#define sipNameNr_writeFileToDisk 1677
#define sipName_writeFileToDisk &sipStrings_Safet[1677]
#define sipNameNr_getDataFileName 1693
#define sipName_getDataFileName &sipStrings_Safet[1693]
#define sipNameNr_getCertFileList 1709
#define sipName_getCertFileList &sipStrings_Safet[1709]
#define sipNameNr_setTemplatePath 1725
#define sipName_setTemplatePath &sipStrings_Safet[1725]
#define sipNameNr_loadEditActions 1741
#define sipName_loadEditActions &sipStrings_Safet[1741]
#define sipNameNr_aspectRatioMode 1757
#define sipName_aspectRatioMode &sipStrings_Safet[1757]
#define sipNameNr_deviceTransform 1773
#define sipName_deviceTransform &sipStrings_Safet[1773]
#define sipNameNr_getXMLDocument 1789
#define sipName_getXMLDocument &sipStrings_Safet[1789]
#define sipNameNr_getSingingTime 1804
#define sipName_getSingingTime &sipStrings_Safet[1804]
#define sipNameNr_getSignerIndex 1819
#define sipName_getSignerIndex &sipStrings_Safet[1819]
#define sipNameNr_syncAttributes 1834
#define sipName_syncAttributes &sipStrings_Safet[1834]
#define sipNameNr_SafetXmlObject 1849
#define sipName_SafetXmlObject &sipStrings_Safet[1849]
#define sipNameNr_sendCheckEmail 1864
#define sipName_sendCheckEmail &sipStrings_Safet[1864]
#define sipNameNr_documentsource 1879
#define sipName_documentsource &sipStrings_Safet[1879]
#define sipNameNr_registerLogout 1894
#define sipName_registerLogout &sipStrings_Safet[1894]
#define sipNameNr_toInputConsole 1909
#define sipName_toInputConsole &sipStrings_Safet[1909]
#define sipNameNr_connectionName 1924
#define sipName_connectionName &sipStrings_Safet[1924]
#define sipNameNr_selectedFilter 1939
#define sipName_selectedFilter &sipStrings_Safet[1939]
#define sipNameNr_setDescription 1954
#define sipName_setDescription &sipStrings_Safet[1954]
#define sipNameNr_SafetWorkflow 1969
#define sipName_SafetWorkflow &sipStrings_Safet[1969]
#define sipNameNr_setCurrentPin 1983
#define sipName_setCurrentPin &sipStrings_Safet[1983]
#define sipNameNr_SafetVariable 1997
#define sipName_SafetVariable &sipStrings_Safet[1997]
#define sipNameNr_versionNumber 2011
#define sipName_versionNumber &sipStrings_Safet[2011]
#define sipNameNr_getValidUntil 2025
#define sipName_getValidUntil &sipStrings_Safet[2025]
#define sipNameNr_decryptString 2039
#define sipName_decryptString &sipStrings_Safet[2039]
#define sipNameNr_initPKCS11Lib 2053
#define sipName_initPKCS11Lib &sipStrings_Safet[2053]
#define sipNameNr_SafetDocument 471
#define sipName_SafetDocument &sipStrings_Safet[471]
#define sipNameNr_getInfoOfUser 2067
#define sipName_getInfoOfUser &sipStrings_Safet[2067]
#define sipNameNr_lastInfoGraph 2081
#define sipName_lastInfoGraph &sipStrings_Safet[2081]
#define sipNameNr_registerLogin 2095
#define sipName_registerLogin &sipStrings_Safet[2095]
#define sipNameNr_setParsValues 2109
#define sipName_setParsValues &sipStrings_Safet[2109]
#define sipNameNr_hostMediaPath 2123
#define sipName_hostMediaPath &sipStrings_Safet[2123]
#define sipNameNr_changedSignal 2137
#define sipName_changedSignal &sipStrings_Safet[2137]
#define sipNameNr_destroyWindow 2151
#define sipName_destroyWindow &sipStrings_Safet[2151]
#define sipNameNr_transformMode 2165
#define sipName_transformMode &sipStrings_Safet[2165]
#define sipNameNr_thresholdTime 2179
#define sipName_thresholdTime &sipStrings_Safet[2179]
#define sipNameNr_connectNotify 1567
#define sipName_connectNotify &sipStrings_Safet[1567]
#define sipNameNr_getDocuments 2193
#define sipName_getDocuments &sipStrings_Safet[2193]
#define sipNameNr_setTokenlink 2206
#define sipName_setTokenlink &sipStrings_Safet[2206]
#define sipNameNr_getSubjectDN 2219
#define sipName_getSubjectDN &sipStrings_Safet[2219]
#define sipNameNr_getAttribute 2232
#define sipName_getAttribute &sipStrings_Safet[2232]
#define sipNameNr_templatePath 2245
#define sipName_templatePath &sipStrings_Safet[2245]
#define sipNameNr_menuCommands 2258
#define sipName_menuCommands &sipStrings_Safet[2258]
#define sipNameNr_setInputPath 2271
#define sipName_setInputPath &sipStrings_Safet[2271]
#define sipNameNr_setMediaPath 2284
#define sipName_setMediaPath &sipStrings_Safet[2284]
#define sipNameNr_currentError 2297
#define sipName_currentError &sipStrings_Safet[2297]
#define sipNameNr_toInputUsers 2310
#define sipName_toInputUsers &sipStrings_Safet[2310]
#define sipNameNr_autoComplete 2323
#define sipName_autoComplete &sipStrings_Safet[2323]
#define sipNameNr_sourceRegion 2336
#define sipName_sourceRegion &sipStrings_Safet[2336]
#define sipNameNr_targetOffset 2349
#define sipName_targetOffset &sipStrings_Safet[2349]
#define sipNameNr_currentTable 2362
#define sipName_currentTable &sipStrings_Safet[2362]
#define sipNameNr_OutputFormat 247
#define sipName_OutputFormat &sipStrings_Safet[247]
#define sipNameNr_serialNumber 2375
#define sipName_serialNumber &sipStrings_Safet[2375]
#define sipNameNr_boundingRect 2388
#define sipName_boundingRect &sipStrings_Safet[2388]
#define sipNameNr_midLineWidth 2401
#define sipName_midLineWidth &sipStrings_Safet[2401]
#define sipNameNr_loadPlugins 2414
#define sipName_loadPlugins &sipStrings_Safet[2414]
#define sipNameNr_getWorkflow 2426
#define sipName_getWorkflow &sipStrings_Safet[2426]
#define sipNameNr_getIssuerDN 2438
#define sipName_getIssuerDN &sipStrings_Safet[2438]
#define sipNameNr_getXmlQuery 2450
#define sipName_getXmlQuery &sipStrings_Safet[2450]
#define sipNameNr_doSaveGraph 2462
#define sipName_doSaveGraph &sipStrings_Safet[2462]
#define sipNameNr_currentDATA 2474
#define sipName_currentDATA &sipStrings_Safet[2474]
#define sipNameNr_currentJSON 2486
#define sipName_currentJSON &sipStrings_Safet[2486]
#define sipNameNr_toInputForm 2498
#define sipName_toInputForm &sipStrings_Safet[2498]
#define sipNameNr_button2Text 2510
#define sipName_button2Text &sipStrings_Safet[2510]
#define sipNameNr_button1Text 2522
#define sipName_button1Text &sipStrings_Safet[2522]
#define sipNameNr_description 2534
#define sipName_description &sipStrings_Safet[2534]
#define sipNameNr_errorColumn 2546
#define sipName_errorColumn &sipStrings_Safet[2546]
#define sipNameNr_customEvent 2558
#define sipName_customEvent &sipStrings_Safet[2558]
#define sipNameNr_eventFilter 2570
#define sipName_eventFilter &sipStrings_Safet[2570]
#define sipNameNr_currentPin 2582
#define sipName_currentPin &sipStrings_Safet[2582]
#define sipNameNr_getValidAt 2593
#define sipName_getValidAt &sipStrings_Safet[2593]
#define sipNameNr_postAction 2604
#define sipName_postAction &sipStrings_Safet[2604]
#define sipNameNr_createBdoc 2615
#define sipName_createBdoc &sipStrings_Safet[2615]
#define sipNameNr_setHostURL 2626
#define sipName_setHostURL &sipStrings_Safet[2626]
#define sipNameNr_convertCSV 2637
#define sipName_convertCSV &sipStrings_Safet[2637]
#define sipNameNr_MainWindow 2648
#define sipName_MainWindow &sipStrings_Safet[2648]
#define sipNameNr_columnSpan 2659
#define sipName_columnSpan &sipStrings_Safet[2659]
#define sipNameNr_constraint 2670
#define sipName_constraint &sipStrings_Safet[2670]
#define sipNameNr_repeatTime 2681
#define sipName_repeatTime &sipStrings_Safet[2681]
#define sipNameNr_fieldWidth 2692
#define sipName_fieldWidth &sipStrings_Safet[2692]
#define sipNameNr_childEvent 2703
#define sipName_childEvent &sipStrings_Safet[2703]
#define sipNameNr_timerEvent 2714
#define sipName_timerEvent &sipStrings_Safet[2714]
#define sipNameNr_listTasks 2725
#define sipName_listTasks &sipStrings_Safet[2725]
#define sipNameNr_SafetYAWL 2735
#define sipName_SafetYAWL &sipStrings_Safet[2735]
#define sipNameNr_setConfig 2745
#define sipName_setConfig &sipStrings_Safet[2745]
#define sipNameNr_tokenlink 2755
#define sipName_tokenlink &sipStrings_Safet[2755]
#define sipNameNr_inputPath 2765
#define sipName_inputPath &sipStrings_Safet[2765]
#define sipNameNr_mediaPath 2775
#define sipName_mediaPath &sipStrings_Safet[2775]
#define sipNameNr_setSource 2785
#define sipName_setSource &sipStrings_Safet[2785]
#define sipNameNr_operation 2795
#define sipName_operation &sipStrings_Safet[2795]
#define sipNameNr_lineWidth 2805
#define sipName_lineWidth &sipStrings_Safet[2805]
#define sipNameNr_beginning 2815
#define sipName_beginning &sipStrings_Safet[2815]
#define sipNameNr_errorLine 2825
#define sipName_errorLine &sipStrings_Safet[2825]
#define sipNameNr_directory 2835
#define sipName_directory &sipStrings_Safet[2835]
#define sipNameNr_alignment 2845
#define sipName_alignment &sipStrings_Safet[2845]
#define sipNameNr_receivers 2855
#define sipName_receivers &sipStrings_Safet[2855]
#define sipNameNr_precision 2865
#define sipName_precision &sipStrings_Safet[2865]
#define sipNameNr_keyvalue 2875
#define sipName_keyvalue &sipStrings_Safet[2875]
#define sipNameNr_setScope 2884
#define sipName_setScope &sipStrings_Safet[2884]
#define sipNameNr_policies 2893
#define sipName_policies &sipStrings_Safet[2893]
#define sipNameNr_menuForm 2902
#define sipName_menuForm &sipStrings_Safet[2902]
#define sipNameNr_addChild 2911
#define sipName_addChild &sipStrings_Safet[2911]
#define sipNameNr_fillRule 2920
#define sipName_fillRule &sipStrings_Safet[2920]
#define sipNameNr_tabArray 2929
#define sipName_tabArray &sipStrings_Safet[2929]
#define sipNameNr_tabStops 2938
#define sipName_tabStops &sipStrings_Safet[2938]
#define sipNameNr_userData 2947
#define sipName_userData &sipStrings_Safet[2947]
#define sipNameNr_shortcut 2956
#define sipName_shortcut &sipStrings_Safet[2956]
#define sipNameNr_errorMsg 2965
#define sipName_errorMsg &sipStrings_Safet[2965]
#define sipNameNr_behavior 2974
#define sipName_behavior &sipStrings_Safet[2974]
#define sipNameNr_position 2983
#define sipName_position &sipStrings_Safet[2983]
#define sipNameNr_fillChar 2992
#define sipName_fillChar &sipStrings_Safet[2992]
#define sipNameNr_property 3001
#define sipName_property &sipStrings_Safet[3001]
#define sipNameNr_openXML 3010
#define sipName_openXML &sipStrings_Safet[3010]
#define sipNameNr_toUtf16 3018
#define sipName_toUtf16 &sipStrings_Safet[3018]
#define sipNameNr_getRole 3026
#define sipName_getRole &sipStrings_Safet[3026]
#define sipNameNr_hostURL 3034
#define sipName_hostURL &sipStrings_Safet[3034]
#define sipNameNr_exposed 3042
#define sipName_exposed &sipStrings_Safet[3042]
#define sipNameNr_button2 3050
#define sipName_button2 &sipStrings_Safet[3050]
#define sipNameNr_button1 3058
#define sipName_button1 &sipStrings_Safet[3058]
#define sipNameNr_quality 3066
#define sipName_quality &sipStrings_Safet[3066]
#define sipNameNr_yMargin 3074
#define sipName_yMargin &sipStrings_Safet[3074]
#define sipNameNr_xMargin 3082
#define sipName_xMargin &sipStrings_Safet[3082]
#define sipNameNr_rowSpan 3090
#define sipName_rowSpan &sipStrings_Safet[3090]
#define sipNameNr_caption 3098
#define sipName_caption &sipStrings_Safet[3098]
#define sipNameNr_options 3106
#define sipName_options &sipStrings_Safet[3106]
#define sipNameNr_setType 3114
#define sipName_setType &sipStrings_Safet[3114]
#define sipNameNr_enabled 3122
#define sipName_enabled &sipStrings_Safet[3122]
#define sipNameNr_filters 3130
#define sipName_filters &sipStrings_Safet[3130]
#define sipNameNr_fields 3138
#define sipName_fields &sipStrings_Safet[3138]
#define sipNameNr_decode 3145
#define sipName_decode &sipStrings_Safet[3145]
#define sipNameNr_logout 3152
#define sipName_logout &sipStrings_Safet[3152]
#define sipNameNr_config 3159
#define sipName_config &sipStrings_Safet[3159]
#define sipNameNr_yRound 3166
#define sipName_yRound &sipStrings_Safet[3166]
#define sipNameNr_xRound 3173
#define sipName_xRound &sipStrings_Safet[3173]
#define sipNameNr_layers 3180
#define sipName_layers &sipStrings_Safet[3180]
#define sipNameNr_window 3187
#define sipName_window &sipStrings_Safet[3187]
#define sipNameNr_sunken 3194
#define sipName_sunken &sipStrings_Safet[3194]
#define sipNameNr_option 3201
#define sipName_option &sipStrings_Safet[3201]
#define sipNameNr_source 1242
#define sipName_source &sipStrings_Safet[1242]
#define sipNameNr_values 3208
#define sipName_values &sipStrings_Safet[3208]
#define sipNameNr_toUtf8 3215
#define sipName_toUtf8 &sipStrings_Safet[3215]
#define sipNameNr_widget 3222
#define sipName_widget &sipStrings_Safet[3222]
#define sipNameNr_proper 3229
#define sipName_proper &sipStrings_Safet[3229]
#define sipNameNr_sender 3236
#define sipName_sender &sipStrings_Safet[3236]
#define sipNameNr_value9 3243
#define sipName_value9 &sipStrings_Safet[3243]
#define sipNameNr_value8 3250
#define sipName_value8 &sipStrings_Safet[3250]
#define sipNameNr_value7 3257
#define sipName_value7 &sipStrings_Safet[3257]
#define sipNameNr_value6 3264
#define sipName_value6 &sipStrings_Safet[3264]
#define sipNameNr_value5 3271
#define sipName_value5 &sipStrings_Safet[3271]
#define sipNameNr_value4 3278
#define sipName_value4 &sipStrings_Safet[3278]
#define sipNameNr_value3 3285
#define sipName_value3 &sipStrings_Safet[3285]
#define sipNameNr_value2 3292
#define sipName_value2 &sipStrings_Safet[3292]
#define sipNameNr_value1 3299
#define sipName_value1 &sipStrings_Safet[3299]
#define sipNameNr_value0 3306
#define sipName_value0 &sipStrings_Safet[3306]
#define sipNameNr_system 3313
#define sipName_system &sipStrings_Safet[3313]
#define sipNameNr_symbol 3320
#define sipName_symbol &sipStrings_Safet[3320]
#define sipNameNr_suffix 3327
#define sipName_suffix &sipStrings_Safet[3327]
#define sipNameNr_prefix 3334
#define sipName_prefix &sipStrings_Safet[3334]
#define sipNameNr_device 3341
#define sipName_device &sipStrings_Safet[3341]
#define sipNameNr_format 3348
#define sipName_format &sipStrings_Safet[3348]
#define sipNameNr_isNull 3355
#define sipName_isNull &sipStrings_Safet[3355]
#define sipNameNr_action 3362
#define sipName_action &sipStrings_Safet[3362]
#define sipNameNr_column 3369
#define sipName_column &sipStrings_Safet[3369]
#define sipNameNr_offset 3376
#define sipName_offset &sipStrings_Safet[3376]
#define sipNameNr_filter 3383
#define sipName_filter &sipStrings_Safet[3383]
#define sipNameNr_object 3390
#define sipName_object &sipStrings_Safet[3390]
#define sipNameNr_parent 3397
#define sipName_parent &sipStrings_Safet[3397]
#define sipNameNr_table 3404
#define sipName_table &sipStrings_Safet[3404]
#define sipNameNr_getCN 3410
#define sipName_getCN &sipStrings_Safet[3410]
#define sipNameNr_login 3416
#define sipName_login &sipStrings_Safet[3416]
#define sipNameNr_setId 3422
#define sipName_setId &sipStrings_Safet[3422]
#define sipNameNr_brush 3428
#define sipName_brush &sipStrings_Safet[3428]
#define sipNameNr_scope 3434
#define sipName_scope &sipStrings_Safet[3434]
#define sipNameNr_hints 3440
#define sipName_hints &sipStrings_Safet[3440]
#define sipNameNr_toHex 3446
#define sipName_toHex &sipStrings_Safet[3446]
#define sipNameNr_flags 3452
#define sipName_flags &sipStrings_Safet[3452]
#define sipNameNr_event 3458
#define sipName_event &sipStrings_Safet[3458]
#define sipNameNr_msecs 3464
#define sipName_msecs &sipStrings_Safet[3464]
#define sipNameNr_state 3470
#define sipName_state &sipStrings_Safet[3470]
#define sipNameNr_Safet 3476
#define sipName_Safet &sipStrings_Safet[3476]
#define sipNameNr_JSON 2493
#define sipName_JSON &sipStrings_Safet[2493]
#define sipNameNr_null 3482
#define sipName_null &sipStrings_Safet[3482]
#define sipNameNr_port 3487
#define sipName_port &sipStrings_Safet[3487]
#define sipNameNr_mode 3492
#define sipName_mode &sipStrings_Safet[3492]
#define sipNameNr_name 3497
#define sipName_name &sipStrings_Safet[3497]
#define sipNameNr_base 3502
#define sipName_base &sipStrings_Safet[3502]
#define sipNameNr_fill 3507
#define sipName_fill &sipStrings_Safet[3507]
#define sipNameNr_from 3512
#define sipName_from &sipStrings_Safet[3512]
#define sipNameNr_sort 3517
#define sipName_sort &sipStrings_Safet[3517]
#define sipNameNr_type 3522
#define sipName_type &sipStrings_Safet[3522]
#define sipNameNr_XML 3014
#define sipName_XML &sipStrings_Safet[3014]
#define sipNameNr_foo 3527
#define sipName_foo &sipStrings_Safet[3527]
#define sipNameNr_ALL 3531
#define sipName_ALL &sipStrings_Safet[3531]
#define sipNameNr_AND 3535
#define sipName_AND &sipStrings_Safet[3535]
#define sipNameNr_log 3539
#define sipName_log &sipStrings_Safet[3539]
#define sipNameNr_SVG 3543
#define sipName_SVG &sipStrings_Safet[3543]
#define sipNameNr_pen 3547
#define sipName_pen &sipStrings_Safet[3547]
#define sipNameNr_key 3551
#define sipName_key &sipStrings_Safet[3551]
#define sipNameNr_end 3555
#define sipName_end &sipStrings_Safet[3555]
#define sipNameNr_map 3559
#define sipName_map &sipStrings_Safet[3559]
#define sipNameNr_pos 3563
#define sipName_pos &sipStrings_Safet[3563]
#define sipNameNr_OR 3567
#define sipName_OR &sipStrings_Safet[3567]
#define sipNameNr_sw 3570
#define sipName_sw &sipStrings_Safet[3570]
#define sipNameNr_sy 3573
#define sipName_sy &sipStrings_Safet[3573]
#define sipNameNr_sx 3576
#define sipName_sx &sipStrings_Safet[3576]
#define sipNameNr_sh 3431
#define sipName_sh &sipStrings_Safet[3431]
#define sipNameNr_cs 3467
#define sipName_cs &sipStrings_Safet[3467]
#define sipNameNr_to 3579
#define sipName_to &sipStrings_Safet[3579]
#define sipNameNr_id 3582
#define sipName_id &sipStrings_Safet[3582]

#define sipMalloc                   sipAPI_Safet->api_malloc
#define sipFree                     sipAPI_Safet->api_free
#define sipBuildResult              sipAPI_Safet->api_build_result
#define sipCallMethod               sipAPI_Safet->api_call_method
#define sipCallProcedureMethod      sipAPI_Safet->api_call_procedure_method
#define sipCallErrorHandler         sipAPI_Safet->api_call_error_handler
#define sipParseResultEx            sipAPI_Safet->api_parse_result_ex
#define sipParseResult              sipAPI_Safet->api_parse_result
#define sipParseArgs                sipAPI_Safet->api_parse_args
#define sipParseKwdArgs             sipAPI_Safet->api_parse_kwd_args
#define sipParsePair                sipAPI_Safet->api_parse_pair
#define sipInstanceDestroyed        sipAPI_Safet->api_instance_destroyed
#define sipConvertFromSequenceIndex sipAPI_Safet->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_Safet->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_Safet->api_convert_to_void_ptr
#define sipAddException             sipAPI_Safet->api_add_exception
#define sipNoFunction               sipAPI_Safet->api_no_function
#define sipNoMethod                 sipAPI_Safet->api_no_method
#define sipAbstractMethod           sipAPI_Safet->api_abstract_method
#define sipBadClass                 sipAPI_Safet->api_bad_class
#define sipBadCatcherResult         sipAPI_Safet->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_Safet->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_Safet->api_bad_operator_arg
#define sipTrace                    sipAPI_Safet->api_trace
#define sipTransferBack             sipAPI_Safet->api_transfer_back
#define sipTransferTo               sipAPI_Safet->api_transfer_to
#define sipTransferBreak            sipAPI_Safet->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_Safet->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_Safet->api_wrapper_type
#define sipWrapperType_Type         sipAPI_Safet->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_Safet->api_voidptr_type
#define sipGetPyObject              sipAPI_Safet->api_get_pyobject
#define sipGetAddress               sipAPI_Safet->api_get_address
#define sipGetMixinAddress          sipAPI_Safet->api_get_mixin_address
#define sipGetCppPtr                sipAPI_Safet->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_Safet->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_Safet->api_is_py_method
#define sipCallHook                 sipAPI_Safet->api_call_hook
#define sipEndThread                sipAPI_Safet->api_end_thread
#define sipConnectRx                sipAPI_Safet->api_connect_rx
#define sipDisconnectRx             sipAPI_Safet->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_Safet->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_Safet->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_Safet->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_Safet->api_add_type_instance
#define sipFreeSipslot              sipAPI_Safet->api_free_sipslot
#define sipSameSlot                 sipAPI_Safet->api_same_slot
#define sipPySlotExtend             sipAPI_Safet->api_pyslot_extend
#define sipConvertRx                sipAPI_Safet->api_convert_rx
#define sipAddDelayedDtor           sipAPI_Safet->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_Safet->api_can_convert_to_type
#define sipConvertToType            sipAPI_Safet->api_convert_to_type
#define sipForceConvertToType       sipAPI_Safet->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_Safet->api_can_convert_to_enum
#define sipConvertToEnum            sipAPI_Safet->api_convert_to_enum
#define sipConvertToBool            sipAPI_Safet->api_convert_to_bool
#define sipReleaseType              sipAPI_Safet->api_release_type
#define sipConvertFromType          sipAPI_Safet->api_convert_from_type
#define sipConvertFromNewType       sipAPI_Safet->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_Safet->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_Safet->api_convert_from_enum
#define sipGetState                 sipAPI_Safet->api_get_state
#define sipExportSymbol             sipAPI_Safet->api_export_symbol
#define sipImportSymbol             sipAPI_Safet->api_import_symbol
#define sipFindType                 sipAPI_Safet->api_find_type
#define sipFindNamedEnum            sipAPI_Safet->api_find_named_enum
#define sipBytes_AsChar             sipAPI_Safet->api_bytes_as_char
#define sipBytes_AsString           sipAPI_Safet->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_Safet->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_Safet->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_Safet->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_Safet->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_Safet->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_Safet->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_Safet->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_Safet->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_Safet->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_Safet->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_Safet->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_Safet->api_invoke_slot
#define sipInvokeSlotEx             sipAPI_Safet->api_invoke_slot_ex
#define sipSaveSlot                 sipAPI_Safet->api_save_slot
#define sipClearAnySlotReference    sipAPI_Safet->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_Safet->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->wt_td->td_cname)
#define sipDeprecated               sipAPI_Safet->api_deprecated
#define sipGetReference             sipAPI_Safet->api_get_reference
#define sipKeepReference            sipAPI_Safet->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_Safet->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_Safet->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_Safet->api_type_from_py_type_object
#define sipTypeScope                sipAPI_Safet->api_type_scope
#define sipResolveTypedef           sipAPI_Safet->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_Safet->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_Safet->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_Safet->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_Safet->api_enable_autoconversion
#define sipEnableOverflowChecking   sipAPI_Safet->api_enable_overflow_checking
#define sipInitMixin                sipAPI_Safet->api_init_mixin
#define sipExportModule             sipAPI_Safet->api_export_module
#define sipInitModule               sipAPI_Safet->api_init_module
#define sipGetInterpreter           sipAPI_Safet->api_get_interpreter
#define sipSetNewUserTypeHandler    sipAPI_Safet->api_set_new_user_type_handler
#define sipSetTypeUserData          sipAPI_Safet->api_set_type_user_data
#define sipGetTypeUserData          sipAPI_Safet->api_get_type_user_data
#define sipPyTypeDict               sipAPI_Safet->api_py_type_dict
#define sipPyTypeName               sipAPI_Safet->api_py_type_name
#define sipGetCFunction             sipAPI_Safet->api_get_c_function
#define sipGetMethod                sipAPI_Safet->api_get_method
#define sipFromMethod               sipAPI_Safet->api_from_method
#define sipGetDate                  sipAPI_Safet->api_get_date
#define sipFromDate                 sipAPI_Safet->api_from_date
#define sipGetDateTime              sipAPI_Safet->api_get_datetime
#define sipFromDateTime             sipAPI_Safet->api_from_datetime
#define sipGetTime                  sipAPI_Safet->api_get_time
#define sipFromTime                 sipAPI_Safet->api_from_time
#define sipIsUserType               sipAPI_Safet->api_is_user_type
#define sipGetFrame                 sipAPI_Safet->api_get_frame
#define sipCheckPluginForType       sipAPI_Safet->api_check_plugin_for_type
#define sipUnicodeNew               sipAPI_Safet->api_unicode_new
#define sipUnicodeWrite             sipAPI_Safet->api_unicode_write
#define sipUnicodeData              sipAPI_Safet->api_unicode_data
#define sipGetBufferInfo            sipAPI_Safet->api_get_buffer_info
#define sipReleaseBufferInfo        sipAPI_Safet->api_release_buffer_info
#define sipIsOwnedByPython          sipAPI_Safet->api_is_owned_by_python
#define sipIsDerivedClass           sipAPI_Safet->api_is_derived_class
#define sipGetUserObject            sipAPI_Safet->api_get_user_object
#define sipSetUserObject            sipAPI_Safet->api_set_user_object
#define sipRegisterEventHandler     sipAPI_Safet->api_register_event_handler
#define sipLong_AsChar              sipAPI_Safet->api_long_as_char
#define sipLong_AsSignedChar        sipAPI_Safet->api_long_as_signed_char
#define sipLong_AsUnsignedChar      sipAPI_Safet->api_long_as_unsigned_char
#define sipLong_AsShort             sipAPI_Safet->api_long_as_short
#define sipLong_AsUnsignedShort     sipAPI_Safet->api_long_as_unsigned_short
#define sipLong_AsInt               sipAPI_Safet->api_long_as_int
#define sipLong_AsUnsignedInt       sipAPI_Safet->api_long_as_unsigned_int
#define sipLong_AsLong              sipAPI_Safet->api_long_as_long
#define sipLong_AsUnsignedLong      sipAPI_Safet->api_long_as_unsigned_long
#define sipLong_AsLongLong          sipAPI_Safet->api_long_as_long_long
#define sipLong_AsUnsignedLongLong  sipAPI_Safet->api_long_as_unsigned_long_long

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_Safet->api_map_string_to_class
#define sipMapIntToClass            sipAPI_Safet->api_map_int_to_class
#define sipFindClass                sipAPI_Safet->api_find_class
#define sipFindMappedType           sipAPI_Safet->api_find_mapped_type
#define sipConvertToArray           sipAPI_Safet->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_Safet->api_convert_to_typed_array
#define sipEnableGC                 sipAPI_Safet->api_enable_gc
#define sipPrintObject              sipAPI_Safet->api_print_object
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_Safet->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->wt_td)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->wt_td, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->wt_td, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->wt_td, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->wt_td, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->wt_td, (t))

/* The strings used by this module. */
extern const char sipStrings_Safet[];

#define sipType_MainWindow sipExportedTypes_Safet[0]
#define sipClass_MainWindow sipExportedTypes_Safet[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_Safet_MainWindow;

#define sipType_SafetXmlObject sipExportedTypes_Safet[9]
#define sipClass_SafetXmlObject sipExportedTypes_Safet[9]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_Safet_SafetXmlObject;

#define sipType_SafetDocument sipExportedTypes_Safet[4]
#define sipClass_SafetDocument sipExportedTypes_Safet[4]->u.td_wrapper_type

#define sipType_SafetDocument_SignatureOperator sipExportedTypes_Safet[5]
#define sipEnum_SafetDocument_SignatureOperator sipExportedTypes_Safet[5]->u.td_py_type

extern sipClassTypeDef sipTypeDef_Safet_SafetDocument;

#define sipType_SafetVariable sipExportedTypes_Safet[6]
#define sipClass_SafetVariable sipExportedTypes_Safet[6]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_Safet_SafetVariable;

#define sipType_SafetYAWL sipExportedTypes_Safet[10]
#define sipClass_SafetYAWL sipExportedTypes_Safet[10]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_Safet_SafetYAWL;

#define sipType_ParsedSqlToData sipExportedTypes_Safet[1]
#define sipClass_ParsedSqlToData sipExportedTypes_Safet[1]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_Safet_ParsedSqlToData;

#define sipType_SafetWorkflow sipExportedTypes_Safet[7]
#define sipClass_SafetWorkflow sipExportedTypes_Safet[7]->u.td_wrapper_type

#define sipType_SafetWorkflow_OutputFormat sipExportedTypes_Safet[8]
#define sipEnum_SafetWorkflow_OutputFormat sipExportedTypes_Safet[8]->u.td_py_type

extern sipClassTypeDef sipTypeDef_Safet_SafetWorkflow;

#define sipType_QList_0101SafetDocument sipExportedTypes_Safet[2]

extern sipMappedTypeDef sipTypeDef_Safet_QList_0101SafetDocument;

#define sipType_QMap_0100QString_0100QString sipExportedTypes_Safet[3]

extern sipMappedTypeDef sipTypeDef_Safet_QMap_0100QString_0100QString;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_Safet;
extern sipExportedModuleDef sipModuleAPI_Safet;
extern sipTypeDef *sipExportedTypes_Safet[];

#define sipType_QObject sipImportedTypes_Safet_QtCore[4].it_td
#define sipClass_QObject sipImportedTypes_Safet_QtCore[4].it_td->u.td_wrapper_type

#define sipType_QByteArray sipImportedTypes_Safet_QtCore[0].it_td
#define sipClass_QByteArray sipImportedTypes_Safet_QtCore[0].it_td->u.td_wrapper_type

#define sipType_QEvent sipImportedTypes_Safet_QtCore[3].it_td
#define sipClass_QEvent sipImportedTypes_Safet_QtCore[3].it_td->u.td_wrapper_type

#define sipType_QTimerEvent sipImportedTypes_Safet_QtCore[7].it_td
#define sipClass_QTimerEvent sipImportedTypes_Safet_QtCore[7].it_td->u.td_wrapper_type

#define sipType_QChildEvent sipImportedTypes_Safet_QtCore[2].it_td
#define sipClass_QChildEvent sipImportedTypes_Safet_QtCore[2].it_td->u.td_wrapper_type

#define sipType_QStringList sipImportedTypes_Safet_QtCore[6].it_td

#define sipType_QString sipImportedTypes_Safet_QtCore[5].it_td

#define sipType_QChar sipImportedTypes_Safet_QtCore[1].it_td
extern sipImportedTypeDef sipImportedTypes_Safet_QtCore[];

#define sipType_QSqlQuery sipImportedTypes_Safet_QtSql[0].it_td
#define sipClass_QSqlQuery sipImportedTypes_Safet_QtSql[0].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_Safet_QtSql[];

#define sipType_QDomElement sipImportedTypes_Safet_QtXml[0].it_td
#define sipClass_QDomElement sipImportedTypes_Safet_QtXml[0].it_td->u.td_wrapper_type
extern sipImportedTypeDef sipImportedTypes_Safet_QtXml[];

typedef const QMetaObject *(*sip_qt_metaobject_func)(sipSimpleWrapper *,sipTypeDef *);
extern sip_qt_metaobject_func sip_Safet_qt_metaobject;

typedef int (*sip_qt_metacall_func)(sipSimpleWrapper *,sipTypeDef *,QMetaObject::Call,int,void **);
extern sip_qt_metacall_func sip_Safet_qt_metacall;

typedef int (*sip_qt_metacast_func)(sipSimpleWrapper *, sipTypeDef *, const char *);
extern sip_qt_metacast_func sip_Safet_qt_metacast;

#endif
