/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.15.5 on Tue Mar 10 20:39:02 2015
 */

#include "sipAPISafet.h"

#line 230 "Safet.sip"
#include "../websafet/src/SafetYAWL.h"
#line 12 "./sipSafetSafetYAWL.cpp"

#line 36 "/usr/share/sip/PyQt4/QtCore/qstring.sip"
#include <qstring.h>
#line 16 "./sipSafetSafetYAWL.cpp"
#line 258 "Safet.sip"
#include "../websafet/src/SafetYAWL.h"
#line 19 "./sipSafetSafetYAWL.cpp"
#line 101 "Safet.sip"
#include "../websafet/src/SafetDocument.h"
#line 22 "./sipSafetSafetYAWL.cpp"
#line 36 "/usr/share/sip/PyQt4/QtCore/qstringlist.sip"
#include <qstringlist.h>
#line 25 "./sipSafetSafetYAWL.cpp"
#line 275 "Safet.sip"
#include "../websafet/src/SafetWorkflow.h"
#line 28 "./sipSafetSafetYAWL.cpp"
#line 345 "/usr/share/sip/PyQt4/QtXml/qdom.sip"
#include <qdom.h>
#line 31 "./sipSafetSafetYAWL.cpp"
#line 31 "/usr/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 34 "./sipSafetSafetYAWL.cpp"
#line 355 "/usr/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 37 "./sipSafetSafetYAWL.cpp"
#line 338 "/usr/share/sip/PyQt4/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 40 "./sipSafetSafetYAWL.cpp"
#line 34 "/usr/share/sip/PyQt4/QtCore/qobject.sip"
#include <qobject.h>
#line 43 "./sipSafetSafetYAWL.cpp"
#line 274 "/usr/share/sip/PyQt4/QtCore/qvariant.sip"
#include <qvariant.h>
#line 46 "./sipSafetSafetYAWL.cpp"
#line 33 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 49 "./sipSafetSafetYAWL.cpp"
#line 37 "/usr/share/sip/PyQt4/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 52 "./sipSafetSafetYAWL.cpp"
#line 35 "/usr/share/sip/PyQt4/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 55 "./sipSafetSafetYAWL.cpp"
#line 120 "/usr/share/sip/PyQt4/QtCore/qlist.sip"
#include <qlist.h>
#line 58 "./sipSafetSafetYAWL.cpp"
#line 31 "/usr/share/sip/PyQt4/QtCore/qthread.sip"
#include <qthread.h>
#line 61 "./sipSafetSafetYAWL.cpp"
#line 35 "/usr/share/sip/PyQt4/QtCore/qregexp.sip"
#include <qregexp.h>
#line 64 "./sipSafetSafetYAWL.cpp"
#line 31 "/usr/share/sip/PyQt4/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 67 "./sipSafetSafetYAWL.cpp"


class sipSafetYAWL : public SafetYAWL
{
public:
    sipSafetYAWL(const QString&);
    virtual ~sipSafetYAWL();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a public method for every protected method visible from
     * this class.
     */
    QObject * sipProtect_sender() const;
    int sipProtect_receivers(const char *) const;
    void sipProtectVirt_timerEvent(bool,QTimerEvent *);
    void sipProtectVirt_childEvent(bool,QChildEvent *);
    void sipProtectVirt_customEvent(bool,QEvent *);
    void sipProtectVirt_connectNotify(bool,const char *);
    void sipProtectVirt_disconnectNotify(bool,const char *);
    int sipProtect_senderSignalIndex() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void disconnectNotify(const char *);
    void connectNotify(const char *);
    void customEvent(QEvent *);
    void childEvent(QChildEvent *);
    void timerEvent(QTimerEvent *);
    bool eventFilter(QObject *,QEvent *);
    bool event(QEvent *);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipSafetYAWL(const sipSafetYAWL &);
    sipSafetYAWL &operator = (const sipSafetYAWL &);

    char sipPyMethods[7];
};

sipSafetYAWL::sipSafetYAWL(const QString& a0): SafetYAWL(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipSafetYAWL::~sipSafetYAWL()
{
    sipCommonDtor(sipPySelf);
}

const QMetaObject *sipSafetYAWL::metaObject() const
{
    return sip_Safet_qt_metaobject(sipPySelf,sipType_SafetYAWL);
}

int sipSafetYAWL::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id = SafetYAWL::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_Safet_qt_metacall(sipPySelf,sipType_SafetYAWL,_c,_id,_a);

    return _id;
}

void *sipSafetYAWL::qt_metacast(const char *_clname)
{
    return (sip_Safet_qt_metacast(sipPySelf, sipType_SafetYAWL, _clname)) ? this : SafetYAWL::qt_metacast(_clname);
}

void sipSafetYAWL::disconnectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
        SafetYAWL::disconnectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_Safet_QtCore->em_virthandlers[24]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipSafetYAWL::connectNotify(const char *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
        SafetYAWL::connectNotify(a0);
        return;
    }

    typedef void (*sipVH_QtCore_24)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const char *);

    ((sipVH_QtCore_24)(sipModuleAPI_Safet_QtCore->em_virthandlers[24]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipSafetYAWL::customEvent(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
        SafetYAWL::customEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_17)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent *);

    ((sipVH_QtCore_17)(sipModuleAPI_Safet_QtCore->em_virthandlers[17]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipSafetYAWL::childEvent(QChildEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
        SafetYAWL::childEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_25)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QChildEvent *);

    ((sipVH_QtCore_25)(sipModuleAPI_Safet_QtCore->em_virthandlers[25]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

void sipSafetYAWL::timerEvent(QTimerEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
        SafetYAWL::timerEvent(a0);
        return;
    }

    typedef void (*sipVH_QtCore_9)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QTimerEvent *);

    ((sipVH_QtCore_9)(sipModuleAPI_Safet_QtCore->em_virthandlers[9]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

bool sipSafetYAWL::eventFilter(QObject *a0,QEvent *a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return SafetYAWL::eventFilter(a0,a1);

    typedef bool (*sipVH_QtCore_18)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QObject *,QEvent *);

    return ((sipVH_QtCore_18)(sipModuleAPI_Safet_QtCore->em_virthandlers[18]))(sipGILState, 0, sipPySelf, sipMeth, a0, a1);
}

bool sipSafetYAWL::event(QEvent *a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return SafetYAWL::event(a0);

    typedef bool (*sipVH_QtCore_5)(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, QEvent *);

    return ((sipVH_QtCore_5)(sipModuleAPI_Safet_QtCore->em_virthandlers[5]))(sipGILState, 0, sipPySelf, sipMeth, a0);
}

QObject * sipSafetYAWL::sipProtect_sender() const
{
    return QObject::sender();
}

int sipSafetYAWL::sipProtect_receivers(const char *a0) const
{
    return QObject::receivers(a0);
}

void sipSafetYAWL::sipProtectVirt_timerEvent(bool sipSelfWasArg,QTimerEvent *a0)
{
    (sipSelfWasArg ? QObject::timerEvent(a0) : timerEvent(a0));
}

void sipSafetYAWL::sipProtectVirt_childEvent(bool sipSelfWasArg,QChildEvent *a0)
{
    (sipSelfWasArg ? QObject::childEvent(a0) : childEvent(a0));
}

void sipSafetYAWL::sipProtectVirt_customEvent(bool sipSelfWasArg,QEvent *a0)
{
    (sipSelfWasArg ? QObject::customEvent(a0) : customEvent(a0));
}

void sipSafetYAWL::sipProtectVirt_connectNotify(bool sipSelfWasArg,const char *a0)
{
    (sipSelfWasArg ? QObject::connectNotify(a0) : connectNotify(a0));
}

void sipSafetYAWL::sipProtectVirt_disconnectNotify(bool sipSelfWasArg,const char *a0)
{
    (sipSelfWasArg ? QObject::disconnectNotify(a0) : disconnectNotify(a0));
}

int sipSafetYAWL::sipProtect_senderSignalIndex() const
{
    return QObject::senderSignalIndex();
}


extern "C" {static PyObject *meth_SafetYAWL_sender(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_sender(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        const sipSafetYAWL *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "B", &sipSelf, sipType_SafetYAWL, &sipCpp))
        {
            QObject *sipRes = 0;

#line 643 "/usr/share/sip/PyQt4/QtCore/qobject.sip"
        typedef QObject *(*helper_func)(QObject *);
        
        static helper_func helper = 0;
        
        if (!helper)
            helper = (helper_func)sipImportSymbol("qpycore_qobject_sender");
        
        // sender() must be called without the GIL to avoid possible deadlocks between
        // the GIL and Qt's internal thread data mutex.
        
        Py_BEGIN_ALLOW_THREADS
        
        #if defined(SIP_PROTECTED_IS_PUBLIC)
        sipRes = sipCpp->sender();
        #else
        sipRes = sipCpp->sipProtect_sender();
        #endif
        
        Py_END_ALLOW_THREADS
        
        if (helper)
            sipRes = helper(sipRes);
#line 342 "./sipSafetSafetYAWL.cpp"

            return sipConvertFromType(sipRes,sipType_QObject,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_sender, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_receivers(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_receivers(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        char * a0;
        const sipSafetYAWL *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "BG", &sipSelf, sipType_SafetYAWL, &sipCpp, &a0))
        {
            int sipRes = 0;

#line 669 "/usr/share/sip/PyQt4/QtCore/qobject.sip"
        // We need to take into account any proxies for Python signals. Import the
        // helper if it hasn't already been done.
        typedef int (*helper_func)(QObject *, const char *, int);
        
        static helper_func helper = 0;
        
        if (!helper)
            helper = (helper_func)sipImportSymbol("qpycore_qobject_receivers");
        
        // PyQt5: Get rid of the const casts.
        if (helper)
        #if defined(SIP_PROTECTED_IS_PUBLIC)
            sipRes = helper(const_cast<QObject *>(sipCpp), a0, sipCpp->receivers(a0));
        #else
            sipRes = helper(const_cast<QObject *>(static_cast<const QObject *>(sipCpp)), a0, sipCpp->sipProtect_receivers(a0));
        #endif
#line 385 "./sipSafetSafetYAWL.cpp"

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_receivers, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_timerEvent(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_timerEvent(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QTimerEvent * a0;
        sipSafetYAWL *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "BJ8", &sipSelf, sipType_SafetYAWL, &sipCpp, sipType_QTimerEvent, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->sipProtectVirt_timerEvent(sipSelfWasArg,a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_timerEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_childEvent(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_childEvent(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QChildEvent * a0;
        sipSafetYAWL *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "BJ8", &sipSelf, sipType_SafetYAWL, &sipCpp, sipType_QChildEvent, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->sipProtectVirt_childEvent(sipSelfWasArg,a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_childEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_customEvent(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_customEvent(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        QEvent * a0;
        sipSafetYAWL *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "BJ8", &sipSelf, sipType_SafetYAWL, &sipCpp, sipType_QEvent, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->sipProtectVirt_customEvent(sipSelfWasArg,a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_customEvent, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_connectNotify(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_connectNotify(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        char * a0;
        sipSafetYAWL *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "BG", &sipSelf, sipType_SafetYAWL, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->sipProtectVirt_connectNotify(sipSelfWasArg,a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_connectNotify, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_disconnectNotify(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_disconnectNotify(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;
    bool sipSelfWasArg = (!sipSelf || sipIsDerived((sipSimpleWrapper *)sipSelf));

    {
        char * a0;
        sipSafetYAWL *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "BG", &sipSelf, sipType_SafetYAWL, &sipCpp, &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->sipProtectVirt_disconnectNotify(sipSelfWasArg,a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_disconnectNotify, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_senderSignalIndex(PyObject *, PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_senderSignalIndex(PyObject *sipSelf, PyObject *sipArgs, PyObject *sipKwds)
{
    PyObject *sipParseErr = NULL;

    {
        const sipSafetYAWL *sipCpp;

        if (sipParseKwdArgs(&sipParseErr, sipArgs, sipKwds, NULL, NULL, "B", &sipSelf, sipType_SafetYAWL, &sipCpp))
        {
            int sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->sipProtect_senderSignalIndex();
            Py_END_ALLOW_THREADS

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_senderSignalIndex, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_openXML(PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_openXML(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        SafetYAWL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_SafetYAWL, &sipCpp, sipType_QString,&a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->openXML(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_openXML, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_convertXMLtoObjects(PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_convertXMLtoObjects(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        SafetYAWL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_SafetYAWL, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->convertXMLtoObjects();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_convertXMLtoObjects, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_getWorkflow(PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_getWorkflow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        SafetYAWL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_SafetYAWL, &sipCpp))
        {
            SafetWorkflow *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->getWorkflow();
            Py_END_ALLOW_THREADS

            return sipConvertFromType(sipRes,sipType_SafetWorkflow,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_getWorkflow, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_openDataSources(PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_openDataSources(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        SafetYAWL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_SafetYAWL, &sipCpp))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->openDataSources();
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_openDataSources, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_setCurrentPin(PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_setCurrentPin(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        SafetYAWL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_SafetYAWL, &sipCpp, sipType_QString,&a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->setCurrentPin(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_setCurrentPin, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_currentPin(PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_currentPin(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const SafetYAWL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_SafetYAWL, &sipCpp))
        {
            QString *sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = new QString(sipCpp->currentPin());
            Py_END_ALLOW_THREADS

            return sipConvertFromNewType(sipRes,sipType_QString,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_currentPin, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_signDocumentsFromData(PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_signDocumentsFromData(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const ParsedSqlToData * a0;
        QString * a1;
        int a1State = 0;
        QStringList * a2;
        int a2State = 0;
        SafetDocument * a3;
        bool a4 = 1;
        SafetYAWL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9J1J1J9|b", &sipSelf, sipType_SafetYAWL, &sipCpp, sipType_ParsedSqlToData, &a0, sipType_QString,&a1, &a1State, sipType_QStringList,&a2, &a2State, sipType_SafetDocument, &a3, &a4))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->signDocumentsFromData(*a0,*a1,*a2,*a3,a4);
            Py_END_ALLOW_THREADS
            sipReleaseType(a1,sipType_QString,a1State);
            sipReleaseType(a2,sipType_QStringList,a2State);

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_signDocumentsFromData, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_verifyDocumentsFromData(PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_verifyDocumentsFromData(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const ParsedSqlToData * a0;
        SafetDocument * a1;
        SafetYAWL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9J9", &sipSelf, sipType_SafetYAWL, &sipCpp, sipType_ParsedSqlToData, &a0, sipType_SafetDocument, &a1))
        {
            bool sipRes;

            Py_BEGIN_ALLOW_THREADS
            sipRes = sipCpp->verifyDocumentsFromData(*a0,*a1);
            Py_END_ALLOW_THREADS

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_verifyDocumentsFromData, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_loadAllConfFiles(PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_loadAllConfFiles(PyObject *, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0 = 3;

        if (sipParseArgs(&sipParseErr, sipArgs, "|i", &a0))
        {
            Py_BEGIN_ALLOW_THREADS
            SafetYAWL::loadAllConfFiles(a0);
            Py_END_ALLOW_THREADS

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_loadAllConfFiles, NULL);

    return NULL;
}


extern "C" {static PyObject *meth_SafetYAWL_loadPlugins(PyObject *, PyObject *);}
static PyObject *meth_SafetYAWL_loadPlugins(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QString * a0;
        int a0State = 0;
        SafetYAWL *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_SafetYAWL, &sipCpp, sipType_QString,&a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp->loadPlugins(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_SafetYAWL, sipName_loadPlugins, NULL);

    return NULL;
}


/* Cast a pointer to a type somewhere in its superclass hierarchy. */
extern "C" {static void *cast_SafetYAWL(void *, const sipTypeDef *);}
static void *cast_SafetYAWL(void *ptr, const sipTypeDef *targetType)
{
    void *res;

    if (targetType == sipType_SafetYAWL)
        return ptr;

    if ((res = ((const sipClassTypeDef *)sipType_SafetXmlObject)->ctd_cast((SafetXmlObject *)(SafetYAWL *)ptr,targetType)) != NULL)
        return res;

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_SafetYAWL(void *, int);}
static void release_SafetYAWL(void *sipCppV,int)
{
    SafetYAWL *sipCpp = reinterpret_cast<SafetYAWL *>(sipCppV);

    Py_BEGIN_ALLOW_THREADS

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();

    Py_END_ALLOW_THREADS
}


extern "C" {static void dealloc_SafetYAWL(sipSimpleWrapper *);}
static void dealloc_SafetYAWL(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerived(sipSelf))
        reinterpret_cast<sipSafetYAWL *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsPyOwned(sipSelf))
    {
        release_SafetYAWL(sipGetAddress(sipSelf),sipSelf->flags);
    }
}


extern "C" {static void *init_type_SafetYAWL(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_SafetYAWL(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
    sipSafetYAWL *sipCpp = 0;

    {
        const QString& a0def = QLatin1String("");
        const QString * a0 = &a0def;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "|J1", sipType_QString,&a0, &a0State))
        {
            Py_BEGIN_ALLOW_THREADS
            sipCpp = new sipSafetYAWL(*a0);
            Py_END_ALLOW_THREADS
            sipReleaseType(const_cast<QString *>(a0),sipType_QString,a0State);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_SafetYAWL[] = {{9, 255, 1}};


static PyMethodDef methods_SafetYAWL[] = {
    {SIP_MLNAME_CAST(sipName_childEvent), (PyCFunction)meth_SafetYAWL_childEvent, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_connectNotify), (PyCFunction)meth_SafetYAWL_connectNotify, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_convertXMLtoObjects), meth_SafetYAWL_convertXMLtoObjects, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_currentPin), meth_SafetYAWL_currentPin, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_customEvent), (PyCFunction)meth_SafetYAWL_customEvent, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_disconnectNotify), (PyCFunction)meth_SafetYAWL_disconnectNotify, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_getWorkflow), meth_SafetYAWL_getWorkflow, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_loadAllConfFiles), meth_SafetYAWL_loadAllConfFiles, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_loadPlugins), meth_SafetYAWL_loadPlugins, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_openDataSources), meth_SafetYAWL_openDataSources, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_openXML), meth_SafetYAWL_openXML, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_receivers), (PyCFunction)meth_SafetYAWL_receivers, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_sender), (PyCFunction)meth_SafetYAWL_sender, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_senderSignalIndex), (PyCFunction)meth_SafetYAWL_senderSignalIndex, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_setCurrentPin), meth_SafetYAWL_setCurrentPin, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_signDocumentsFromData), meth_SafetYAWL_signDocumentsFromData, METH_VARARGS, NULL},
    {SIP_MLNAME_CAST(sipName_timerEvent), (PyCFunction)meth_SafetYAWL_timerEvent, METH_VARARGS|METH_KEYWORDS, NULL},
    {SIP_MLNAME_CAST(sipName_verifyDocumentsFromData), meth_SafetYAWL_verifyDocumentsFromData, METH_VARARGS, NULL}
};


pyqt4ClassTypeDef sipTypeDef_Safet_SafetYAWL = {
{
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_CLASS,
        sipNameNr_SafetYAWL,
        {0}
    },
    {
        sipNameNr_SafetYAWL,
        {0, 0, 1},
        18, methods_SafetYAWL,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_SafetYAWL,
    0,
    init_type_SafetYAWL,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_SafetYAWL,
    0,
    0,
    0,
    release_SafetYAWL,
    cast_SafetYAWL,
    0,
    0,
    0,
    0,
    0,
    0
},
    &SafetYAWL::staticMetaObject,
    0,
    0
};
