/*
 * Module code.
 *
 * Generated by SIP 4.15.5 on Tue Mar 10 20:39:02 2015
 */

#include "sipAPISafet.h"

#line 34 "/usr/share/sip/PyQt4/QtCore/qobject.sip"
#include <qobject.h>
#line 12 "./sipSafetcmodule.cpp"
#line 89 "Safet.sip"
#include "../websafet/src/SafetXmlObject.h"
#line 15 "./sipSafetcmodule.cpp"
#line 258 "Safet.sip"
#include "../websafet/src/SafetYAWL.h"
#line 18 "./sipSafetcmodule.cpp"

/* Define the strings used by this module. */
const char sipStrings_Safet[] = {
    'n', 'u', 'm', 'b', 'e', 'r', 'O', 'f', 'S', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 's', 'O', 'n', 'O', 'p', 'e', 'n', 'X', 'A', 'd', 'E', 'S', 'C', 'o', 'n', 't', 'a', 'i', 'n', 'e', 'r', 0,
    'n', 'u', 'm', 'b', 'e', 'r', 'O', 'f', 'D', 'a', 't', 'a', 'F', 'i', 'l', 'e', 'O', 'n', 'O', 'p', 'e', 'n', 'X', 'A', 'd', 'E', 'S', 'C', 'o', 'n', 't', 'a', 'i', 'n', 'e', 'r', 0,
    'a', 'd', 'd', 'S', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 'T', 'o', 'E', 'x', 'i', 's', 't', 'i', 'n', 'g', 'D', 'i', 'g', 'i', 'd', 'o', 'c', 'F', 'i', 'l', 'e', 0,
    'S', 'a', 'f', 'e', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', ':', ':', 'S', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 'O', 'p', 'e', 'r', 'a', 't', 'o', 'r', 0,
    'g', 'e', 't', 'S', 'i', 'g', 'n', 'e', 'r', 'C', 'e', 'r', 't', 'i', 'f', 'i', 'c', 'a', 't', 'e', 'I', 's', 's', 'u', 'e', 'r', 'N', 'a', 'm', 'e', 0,
    'g', 'e', 't', 'C', 'o', 'm', 'm', 'o', 'n', 'N', 'a', 'm', 'e', 'F', 'r', 'o', 'm', 'C', 'e', 'r', 't', 'i', 'f', 'i', 'c', 'a', 't', 'e', 0,
    'P', 'y', 'Q', 't', '4', '.', 'Q', 't', 'C', 'o', 'r', 'e', '.', 'p', 'y', 'q', 't', 'W', 'r', 'a', 'p', 'p', 'e', 'r', 'T', 'y', 'p', 'e', 0,
    'S', 'a', 'f', 'e', 't', 'W', 'o', 'r', 'k', 'f', 'l', 'o', 'w', ':', ':', 'O', 'u', 't', 'p', 'u', 't', 'F', 'o', 'r', 'm', 'a', 't', 0,
    'v', 'e', 'r', 'i', 'f', 'y', 'S', 'i', 'g', 'n', 'M', 'a', 'd', 'e', 'W', 'i', 't', 'h', 'S', 'm', 'a', 'r', 't', 'C', 'a', 'r', 'd', 0,
    'g', 'e', 't', 'S', 'i', 'g', 'n', 'e', 'r', 'C', 'e', 'r', 't', 'i', 'f', 'i', 'c', 'a', 't', 'e', 'S', 'e', 'r', 'i', 'a', 'l', 0,
    'n', 'u', 'm', 'b', 'e', 'r', 'O', 'f', 'D', 'a', 't', 'a', 'F', 'i', 'l', 'e', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 's', 0,
    'g', 'e', 't', 'P', 'o', 's', 't', 'a', 'l', 'C', 'o', 'd', 'e', 'O', 'f', 'S', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 0,
    's', 'i', 'g', 'n', 'W', 'i', 't', 'h', 'P', 'r', 'i', 'v', 'a', 't', 'e', 'K', 'e', 'y', 'O', 'n', 'F', 'i', 'l', 'e', 0,
    'v', 'e', 'r', 'i', 'f', 'y', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 's', 'F', 'r', 'o', 'm', 'D', 'a', 't', 'a', 0,
    'c', 'r', 'e', 'a', 't', 'e', 'X', 'M', 'L', 'F', 'i', 'l', 'e', 'F', 'r', 'o', 'm', 'Q', 'u', 'e', 'r', 'y', 0,
    'a', 'u', 't', 'h', 'o', 'r', 'i', 't', 'y', 'K', 'e', 'y', 'I', 'd', 'e', 'n', 't', 'i', 'f', 'i', 'e', 'r', 0,
    's', 'e', 't', 'P', 'a', 't', 'h', 'O', 'f', 'S', 'a', 'f', 'e', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 0,
    'g', 'e', 't', 'P', 'a', 't', 'h', 'O', 'f', 'S', 'a', 'f', 'e', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 0,
    'g', 'e', 't', 'S', 'i', 'n', 'g', 'i', 'n', 'g', 'T', 'i', 'm', 'e', 'O', 'n', 'l', 'y', 'H', 'o', 'u', 'r', 0,
    'g', 'e', 't', 'S', 'i', 'n', 'g', 'i', 'n', 'g', 'T', 'i', 'm', 'e', 'O', 'n', 'l', 'y', 'D', 'a', 't', 'e', 0,
    'g', 'e', 't', 'N', 'u', 'm', 'b', 'e', 'r', 'O', 'f', 'P', 'r', 'i', 'v', 'a', 't', 'e', 'K', 'e', 'y', 's', 0,
    'g', 'e', 't', 'C', 'o', 'm', 'm', 'o', 'n', 'N', 'a', 'm', 'e', 'O', 'f', 'S', 'i', 'g', 'n', 'e', 'r', 's', 0,
    'i', 'n', 'i', 't', 'D', 'i', 'g', 'i', 'd', 'o', 'c', 'C', 'o', 'n', 'f', 'i', 'g', 'S', 't', 'o', 'r', 'e', 0,
    'Q', 'L', 'i', 's', 't', '<', 'S', 'a', 'f', 'e', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', '*', '>', 0,
    'Q', 'M', 'a', 'p', '<', 'Q', 'S', 't', 'r', 'i', 'n', 'g', ',', 'Q', 'S', 't', 'r', 'i', 'n', 'g', '>', 0,
    's', 'i', 'g', 'n', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 's', 'F', 'r', 'o', 'm', 'D', 'a', 't', 'a', 0,
    'g', 'e', 't', 'P', 'u', 'b', 'l', 'i', 'c', 'K', 'e', 'y', 'A', 'l', 'g', 'o', 'r', 'i', 't', 'h', 'm', 0,
    'g', 'e', 't', 'C', 'o', 'u', 'n', 't', 'r', 'y', 'O', 'f', 'S', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 0,
    'g', 'e', 't', 'D', 'a', 't', 'a', 'B', 'a', 's', 'e', 'T', 'a', 'b', 'l', 'e', 'N', 'a', 'm', 'e', 's', 0,
    'c', 'h', 'a', 'n', 'g', 'e', 'C', 'o', 'n', 'n', 'X', 'M', 'L', 'W', 'o', 'r', 'k', 'f', 'l', 'o', 'w', 0,
    's', 'u', 'b', 'j', 'e', 'c', 't', 'K', 'e', 'y', 'I', 'd', 'e', 'n', 't', 'i', 'f', 'i', 'e', 'r', 0,
    'c', 'r', 'e', 'a', 't', 'e', 'X', 'M', 'L', 'F', 'i', 'l', 'e', 'F', 'r', 'o', 'm', 'S', 'Q', 'L', 0,
    'd', 'e', 'l', 'N', 'o', 'd', 'e', 'T', 'o', 'X', 'M', 'L', 'W', 'o', 'r', 'k', 'f', 'l', 'o', 'w', 0,
    'a', 'd', 'd', 'N', 'o', 'd', 'e', 'T', 'o', 'X', 'M', 'L', 'W', 'o', 'r', 'k', 'f', 'l', 'o', 'w', 0,
    'a', 'd', 'd', 'I', 'n', 'f', 'o', 'G', 'r', 'a', 'p', 'h', 'D', 'a', 't', 'e', 'T', 'e', 'x', 't', 0,
    'c', 'o', 'n', 'v', 'e', 'r', 't', 'X', 'M', 'L', 't', 'o', 'O', 'b', 'j', 'e', 'c', 't', 's', 0,
    'g', 'e', 't', 'S', 't', 'a', 't', 'e', 'O', 'f', 'S', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 0,
    't', 'e', 's', 't', 'S', 'm', 'a', 'r', 't', 'C', 'a', 'r', 'd', 'D', 'r', 'i', 'v', 'e', 'r', 0,
    'g', 'e', 't', 'D', 'a', 't', 'a', 'F', 'i', 'l', 'e', 'M', 'i', 'm', 'e', 'T', 'y', 'p', 'e', 0,
    'd', 'o', 'S', 'a', 'v', 'e', 'C', 'o', 'n', 'f', 'i', 'g', 'u', 'r', 'a', 't', 'i', 'o', 'n', 0,
    'd', 'o', 'L', 'o', 'a', 'd', 'C', 'o', 'n', 'f', 'i', 'g', 'u', 'r', 'a', 't', 'i', 'o', 'n', 0,
    'd', 'e', 'f', 'a', 'u', 'l', 't', 'B', 'u', 't', 't', 'o', 'n', 'N', 'u', 'm', 'b', 'e', 'r', 0,
    'g', 'e', 't', 'P', 'u', 'b', 'l', 'i', 'c', 'K', 'e', 'y', 'L', 'e', 'n', 'g', 't', 'h', 0,
    'g', 'e', 't', 'S', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 'F', 'o', 'r', 'm', 'a', 't', 0,
    's', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 'L', 'o', 'c', 'a', 't', 'i', 'o', 'n', 's', 0,
    'g', 'e', 't', 'C', 'i', 't', 'y', 'O', 'f', 'S', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 0,
    'r', 'e', 't', 'u', 'r', 'n', 'F', 'i', 'l', 'e', 'T', 'o', 'S', 't', 'r', 'i', 'n', 'g', 0,
    'c', 'h', 'e', 'c', 'k', 'A', 'n', 'd', 'E', 'x', 'e', 'c', 'E', 'v', 'e', 'n', 't', 's', 0,
    'l', 'o', 'a', 'd', 'R', 'e', 'p', 'o', 'r', 't', 'T', 'e', 'm', 'p', 'l', 'a', 't', 'e', 0,
    'g', 'e', 'n', 'e', 'r', 'a', 't', 'e', 'M', 'o', 'd', 'i', 'f', 'y', 'H', 'T', 'M', 'L', 0,
    'g', 'e', 'n', 'e', 'r', 'a', 't', 'e', 'F', 'o', 'r', 'm', 'F', 'o', 'o', 't', 'e', 'r', 0,
    'e', 's', 'c', 'a', 'p', 'e', 'B', 'u', 't', 't', 'o', 'n', 'N', 'u', 'm', 'b', 'e', 'r', 0,
    's', 'e', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 's', 'o', 'u', 'r', 'c', 'e', 0,
    's', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 'L', 'o', 'c', 'a', 't', 'i', 'o', 'n', 0,
    'c', 'o', 'n', 'n', 'e', 'c', 't', 'T', 'o', 'D', 'a', 't', 'a', 'B', 'a', 's', 'e', 0,
    'g', 'e', 't', 'D', 'a', 't', 'a', 'F', 'i', 'l', 'e', 'L', 'e', 'n', 'g', 't', 'h', 0,
    'c', 'h', 'e', 'c', 'k', 'U', 's', 'e', 'r', 'R', 'e', 'g', 'i', 's', 't', 'e', 'r', 0,
    'c', 'u', 'r', 'r', 'e', 'n', 't', 'G', 'r', 'a', 'p', 'h', 'T', 'i', 't', 'l', 'e', 0,
    's', 'e', 't', 'C', 'o', 'n', 'f', 'f', 'i', 'l', 'e', 'V', 'a', 'l', 'u', 'e', 's', 0,
    'g', 'e', 't', 'F', 'l', 'o', 'w', 'P', 'a', 'r', 'a', 'm', 'e', 't', 'e', 'r', 's', 0,
    'd', 'e', 's', 't', 'r', 'o', 'y', 'S', 'u', 'b', 'W', 'i', 'n', 'd', 'o', 'w', 's', 0,
    's', 'e', 'n', 'd', 'e', 'r', 'S', 'i', 'g', 'n', 'a', 'l', 'I', 'n', 'd', 'e', 'x', 0,
    'l', 'o', 'a', 'd', 'A', 'l', 'l', 'C', 'o', 'n', 'f', 'F', 'i', 'l', 'e', 's', 0,
    'g', 'e', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 'C', 'o', 'u', 'n', 't', 0,
    'e', 'n', 'h', 'a', 'n', 'c', 'e', 'd', 'K', 'e', 'y', 'U', 's', 'a', 'g', 'e', 0,
    'g', 'e', 't', 'S', 'i', 'g', 'n', 'a', 't', 'u', 'r', 'e', 'T', 'y', 'p', 'e', 0,
    'g', 'e', 't', 'T', 'e', 'm', 'p', 'N', 'a', 'm', 'e', 'F', 'i', 'l', 'e', 's', 0,
    'g', 'e', 'n', 'e', 'r', 'a', 't', 'e', 'F', 'o', 'r', 'm', 'H', 'e', 'a', 'd', 0,
    's', 'e', 't', 'H', 'o', 's', 't', 'M', 'e', 'd', 'i', 'a', 'P', 'a', 't', 'h', 0,
    'd', 'e', 's', 't', 'r', 'o', 'y', 'O', 'l', 'd', 'W', 'i', 'n', 'd', 'o', 'w', 0,
    'i', 'n', 'i', 't', 'i', 'a', 'l', 'i', 'z', 'e', 'W', 'i', 'n', 'd', 'o', 'w', 0,
    'd', 'i', 's', 'c', 'o', 'n', 'n', 'e', 'c', 't', 'N', 'o', 't', 'i', 'f', 'y', 0,
    'P', 'a', 'r', 's', 'e', 'd', 'S', 'q', 'l', 'T', 'o', 'D', 'a', 't', 'a', 0,
    'o', 'p', 'e', 'n', 'D', 'a', 't', 'a', 'S', 'o', 'u', 'r', 'c', 'e', 's', 0,
    'w', 'r', 'i', 't', 'e', 'X', '5', '0', '9', 'T', 'o', 'F', 'i', 'l', 'e', 0,
    's', 'u', 'b', 'j', 'e', 'c', 't', 'I', 'n', 'f', 'o', 'U', 't', 'f', '8', 0,
    'g', 'e', 't', 'C', 'o', 'u', 'n', 't', 'O', 'f', 'R', 'o', 'l', 'e', 's', 0,
    'd', 'e', 'c', 'r', 'y', 'p', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 0,
    'w', 'r', 'i', 't', 'e', 'F', 'i', 'l', 'e', 'T', 'o', 'D', 'i', 's', 'k', 0,
    'g', 'e', 't', 'D', 'a', 't', 'a', 'F', 'i', 'l', 'e', 'N', 'a', 'm', 'e', 0,
    'g', 'e', 't', 'C', 'e', 'r', 't', 'F', 'i', 'l', 'e', 'L', 'i', 's', 't', 0,
    's', 'e', 't', 'T', 'e', 'm', 'p', 'l', 'a', 't', 'e', 'P', 'a', 't', 'h', 0,
    'l', 'o', 'a', 'd', 'E', 'd', 'i', 't', 'A', 'c', 't', 'i', 'o', 'n', 's', 0,
    'a', 's', 'p', 'e', 'c', 't', 'R', 'a', 't', 'i', 'o', 'M', 'o', 'd', 'e', 0,
    'd', 'e', 'v', 'i', 'c', 'e', 'T', 'r', 'a', 'n', 's', 'f', 'o', 'r', 'm', 0,
    'g', 'e', 't', 'X', 'M', 'L', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 0,
    'g', 'e', 't', 'S', 'i', 'n', 'g', 'i', 'n', 'g', 'T', 'i', 'm', 'e', 0,
    'g', 'e', 't', 'S', 'i', 'g', 'n', 'e', 'r', 'I', 'n', 'd', 'e', 'x', 0,
    's', 'y', 'n', 'c', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 's', 0,
    'S', 'a', 'f', 'e', 't', 'X', 'm', 'l', 'O', 'b', 'j', 'e', 'c', 't', 0,
    's', 'e', 'n', 'd', 'C', 'h', 'e', 'c', 'k', 'E', 'm', 'a', 'i', 'l', 0,
    'd', 'o', 'c', 'u', 'm', 'e', 'n', 't', 's', 'o', 'u', 'r', 'c', 'e', 0,
    'r', 'e', 'g', 'i', 's', 't', 'e', 'r', 'L', 'o', 'g', 'o', 'u', 't', 0,
    't', 'o', 'I', 'n', 'p', 'u', 't', 'C', 'o', 'n', 's', 'o', 'l', 'e', 0,
    'c', 'o', 'n', 'n', 'e', 'c', 't', 'i', 'o', 'n', 'N', 'a', 'm', 'e', 0,
    's', 'e', 'l', 'e', 'c', 't', 'e', 'd', 'F', 'i', 'l', 't', 'e', 'r', 0,
    's', 'e', 't', 'D', 'e', 's', 'c', 'r', 'i', 'p', 't', 'i', 'o', 'n', 0,
    'S', 'a', 'f', 'e', 't', 'W', 'o', 'r', 'k', 'f', 'l', 'o', 'w', 0,
    's', 'e', 't', 'C', 'u', 'r', 'r', 'e', 'n', 't', 'P', 'i', 'n', 0,
    'S', 'a', 'f', 'e', 't', 'V', 'a', 'r', 'i', 'a', 'b', 'l', 'e', 0,
    'v', 'e', 'r', 's', 'i', 'o', 'n', 'N', 'u', 'm', 'b', 'e', 'r', 0,
    'g', 'e', 't', 'V', 'a', 'l', 'i', 'd', 'U', 'n', 't', 'i', 'l', 0,
    'd', 'e', 'c', 'r', 'y', 'p', 't', 'S', 't', 'r', 'i', 'n', 'g', 0,
    'i', 'n', 'i', 't', 'P', 'K', 'C', 'S', '1', '1', 'L', 'i', 'b', 0,
    'g', 'e', 't', 'I', 'n', 'f', 'o', 'O', 'f', 'U', 's', 'e', 'r', 0,
    'l', 'a', 's', 't', 'I', 'n', 'f', 'o', 'G', 'r', 'a', 'p', 'h', 0,
    'r', 'e', 'g', 'i', 's', 't', 'e', 'r', 'L', 'o', 'g', 'i', 'n', 0,
    's', 'e', 't', 'P', 'a', 'r', 's', 'V', 'a', 'l', 'u', 'e', 's', 0,
    'h', 'o', 's', 't', 'M', 'e', 'd', 'i', 'a', 'P', 'a', 't', 'h', 0,
    'c', 'h', 'a', 'n', 'g', 'e', 'd', 'S', 'i', 'g', 'n', 'a', 'l', 0,
    'd', 'e', 's', 't', 'r', 'o', 'y', 'W', 'i', 'n', 'd', 'o', 'w', 0,
    't', 'r', 'a', 'n', 's', 'f', 'o', 'r', 'm', 'M', 'o', 'd', 'e', 0,
    't', 'h', 'r', 'e', 's', 'h', 'o', 'l', 'd', 'T', 'i', 'm', 'e', 0,
    'g', 'e', 't', 'D', 'o', 'c', 'u', 'm', 'e', 'n', 't', 's', 0,
    's', 'e', 't', 'T', 'o', 'k', 'e', 'n', 'l', 'i', 'n', 'k', 0,
    'g', 'e', 't', 'S', 'u', 'b', 'j', 'e', 'c', 't', 'D', 'N', 0,
    'g', 'e', 't', 'A', 't', 't', 'r', 'i', 'b', 'u', 't', 'e', 0,
    't', 'e', 'm', 'p', 'l', 'a', 't', 'e', 'P', 'a', 't', 'h', 0,
    'm', 'e', 'n', 'u', 'C', 'o', 'm', 'm', 'a', 'n', 'd', 's', 0,
    's', 'e', 't', 'I', 'n', 'p', 'u', 't', 'P', 'a', 't', 'h', 0,
    's', 'e', 't', 'M', 'e', 'd', 'i', 'a', 'P', 'a', 't', 'h', 0,
    'c', 'u', 'r', 'r', 'e', 'n', 't', 'E', 'r', 'r', 'o', 'r', 0,
    't', 'o', 'I', 'n', 'p', 'u', 't', 'U', 's', 'e', 'r', 's', 0,
    'a', 'u', 't', 'o', 'C', 'o', 'm', 'p', 'l', 'e', 't', 'e', 0,
    's', 'o', 'u', 'r', 'c', 'e', 'R', 'e', 'g', 'i', 'o', 'n', 0,
    't', 'a', 'r', 'g', 'e', 't', 'O', 'f', 'f', 's', 'e', 't', 0,
    'c', 'u', 'r', 'r', 'e', 'n', 't', 'T', 'a', 'b', 'l', 'e', 0,
    's', 'e', 'r', 'i', 'a', 'l', 'N', 'u', 'm', 'b', 'e', 'r', 0,
    'b', 'o', 'u', 'n', 'd', 'i', 'n', 'g', 'R', 'e', 'c', 't', 0,
    'm', 'i', 'd', 'L', 'i', 'n', 'e', 'W', 'i', 'd', 't', 'h', 0,
    'l', 'o', 'a', 'd', 'P', 'l', 'u', 'g', 'i', 'n', 's', 0,
    'g', 'e', 't', 'W', 'o', 'r', 'k', 'f', 'l', 'o', 'w', 0,
    'g', 'e', 't', 'I', 's', 's', 'u', 'e', 'r', 'D', 'N', 0,
    'g', 'e', 't', 'X', 'm', 'l', 'Q', 'u', 'e', 'r', 'y', 0,
    'd', 'o', 'S', 'a', 'v', 'e', 'G', 'r', 'a', 'p', 'h', 0,
    'c', 'u', 'r', 'r', 'e', 'n', 't', 'D', 'A', 'T', 'A', 0,
    'c', 'u', 'r', 'r', 'e', 'n', 't', 'J', 'S', 'O', 'N', 0,
    't', 'o', 'I', 'n', 'p', 'u', 't', 'F', 'o', 'r', 'm', 0,
    'b', 'u', 't', 't', 'o', 'n', '2', 'T', 'e', 'x', 't', 0,
    'b', 'u', 't', 't', 'o', 'n', '1', 'T', 'e', 'x', 't', 0,
    'd', 'e', 's', 'c', 'r', 'i', 'p', 't', 'i', 'o', 'n', 0,
    'e', 'r', 'r', 'o', 'r', 'C', 'o', 'l', 'u', 'm', 'n', 0,
    'c', 'u', 's', 't', 'o', 'm', 'E', 'v', 'e', 'n', 't', 0,
    'e', 'v', 'e', 'n', 't', 'F', 'i', 'l', 't', 'e', 'r', 0,
    'c', 'u', 'r', 'r', 'e', 'n', 't', 'P', 'i', 'n', 0,
    'g', 'e', 't', 'V', 'a', 'l', 'i', 'd', 'A', 't', 0,
    'p', 'o', 's', 't', 'A', 'c', 't', 'i', 'o', 'n', 0,
    'c', 'r', 'e', 'a', 't', 'e', 'B', 'd', 'o', 'c', 0,
    's', 'e', 't', 'H', 'o', 's', 't', 'U', 'R', 'L', 0,
    'M', 'a', 'i', 'n', 'W', 'i', 'n', 'd', 'o', 'w', 0,
    'c', 'o', 'l', 'u', 'm', 'n', 'S', 'p', 'a', 'n', 0,
    'c', 'o', 'n', 's', 't', 'r', 'a', 'i', 'n', 't', 0,
    'r', 'e', 'p', 'e', 'a', 't', 'T', 'i', 'm', 'e', 0,
    'f', 'i', 'e', 'l', 'd', 'W', 'i', 'd', 't', 'h', 0,
    'c', 'h', 'i', 'l', 'd', 'E', 'v', 'e', 'n', 't', 0,
    't', 'i', 'm', 'e', 'r', 'E', 'v', 'e', 'n', 't', 0,
    'l', 'i', 's', 't', 'T', 'a', 's', 'k', 's', 0,
    'S', 'a', 'f', 'e', 't', 'Y', 'A', 'W', 'L', 0,
    's', 'e', 't', 'C', 'o', 'n', 'f', 'i', 'g', 0,
    't', 'o', 'k', 'e', 'n', 'l', 'i', 'n', 'k', 0,
    'i', 'n', 'p', 'u', 't', 'P', 'a', 't', 'h', 0,
    'm', 'e', 'd', 'i', 'a', 'P', 'a', 't', 'h', 0,
    's', 'e', 't', 'S', 'o', 'u', 'r', 'c', 'e', 0,
    'o', 'p', 'e', 'r', 'a', 't', 'i', 'o', 'n', 0,
    'l', 'i', 'n', 'e', 'W', 'i', 'd', 't', 'h', 0,
    'b', 'e', 'g', 'i', 'n', 'n', 'i', 'n', 'g', 0,
    'e', 'r', 'r', 'o', 'r', 'L', 'i', 'n', 'e', 0,
    'd', 'i', 'r', 'e', 'c', 't', 'o', 'r', 'y', 0,
    'a', 'l', 'i', 'g', 'n', 'm', 'e', 'n', 't', 0,
    'r', 'e', 'c', 'e', 'i', 'v', 'e', 'r', 's', 0,
    'p', 'r', 'e', 'c', 'i', 's', 'i', 'o', 'n', 0,
    'k', 'e', 'y', 'v', 'a', 'l', 'u', 'e', 0,
    's', 'e', 't', 'S', 'c', 'o', 'p', 'e', 0,
    'p', 'o', 'l', 'i', 'c', 'i', 'e', 's', 0,
    'm', 'e', 'n', 'u', 'F', 'o', 'r', 'm', 0,
    'a', 'd', 'd', 'C', 'h', 'i', 'l', 'd', 0,
    'f', 'i', 'l', 'l', 'R', 'u', 'l', 'e', 0,
    't', 'a', 'b', 'A', 'r', 'r', 'a', 'y', 0,
    't', 'a', 'b', 'S', 't', 'o', 'p', 's', 0,
    'u', 's', 'e', 'r', 'D', 'a', 't', 'a', 0,
    's', 'h', 'o', 'r', 't', 'c', 'u', 't', 0,
    'e', 'r', 'r', 'o', 'r', 'M', 's', 'g', 0,
    'b', 'e', 'h', 'a', 'v', 'i', 'o', 'r', 0,
    'p', 'o', 's', 'i', 't', 'i', 'o', 'n', 0,
    'f', 'i', 'l', 'l', 'C', 'h', 'a', 'r', 0,
    'p', 'r', 'o', 'p', 'e', 'r', 't', 'y', 0,
    'o', 'p', 'e', 'n', 'X', 'M', 'L', 0,
    't', 'o', 'U', 't', 'f', '1', '6', 0,
    'g', 'e', 't', 'R', 'o', 'l', 'e', 0,
    'h', 'o', 's', 't', 'U', 'R', 'L', 0,
    'e', 'x', 'p', 'o', 's', 'e', 'd', 0,
    'b', 'u', 't', 't', 'o', 'n', '2', 0,
    'b', 'u', 't', 't', 'o', 'n', '1', 0,
    'q', 'u', 'a', 'l', 'i', 't', 'y', 0,
    'y', 'M', 'a', 'r', 'g', 'i', 'n', 0,
    'x', 'M', 'a', 'r', 'g', 'i', 'n', 0,
    'r', 'o', 'w', 'S', 'p', 'a', 'n', 0,
    'c', 'a', 'p', 't', 'i', 'o', 'n', 0,
    'o', 'p', 't', 'i', 'o', 'n', 's', 0,
    's', 'e', 't', 'T', 'y', 'p', 'e', 0,
    'e', 'n', 'a', 'b', 'l', 'e', 'd', 0,
    'f', 'i', 'l', 't', 'e', 'r', 's', 0,
    'f', 'i', 'e', 'l', 'd', 's', 0,
    'd', 'e', 'c', 'o', 'd', 'e', 0,
    'l', 'o', 'g', 'o', 'u', 't', 0,
    'c', 'o', 'n', 'f', 'i', 'g', 0,
    'y', 'R', 'o', 'u', 'n', 'd', 0,
    'x', 'R', 'o', 'u', 'n', 'd', 0,
    'l', 'a', 'y', 'e', 'r', 's', 0,
    'w', 'i', 'n', 'd', 'o', 'w', 0,
    's', 'u', 'n', 'k', 'e', 'n', 0,
    'o', 'p', 't', 'i', 'o', 'n', 0,
    'v', 'a', 'l', 'u', 'e', 's', 0,
    't', 'o', 'U', 't', 'f', '8', 0,
    'w', 'i', 'd', 'g', 'e', 't', 0,
    'p', 'r', 'o', 'p', 'e', 'r', 0,
    's', 'e', 'n', 'd', 'e', 'r', 0,
    'v', 'a', 'l', 'u', 'e', '9', 0,
    'v', 'a', 'l', 'u', 'e', '8', 0,
    'v', 'a', 'l', 'u', 'e', '7', 0,
    'v', 'a', 'l', 'u', 'e', '6', 0,
    'v', 'a', 'l', 'u', 'e', '5', 0,
    'v', 'a', 'l', 'u', 'e', '4', 0,
    'v', 'a', 'l', 'u', 'e', '3', 0,
    'v', 'a', 'l', 'u', 'e', '0', 0,
    's', 'y', 's', 't', 'e', 'm', 0,
    's', 'y', 'm', 'b', 'o', 'l', 0,
    's', 'u', 'f', 'f', 'i', 'x', 0,
    'p', 'r', 'e', 'f', 'i', 'x', 0,
    'd', 'e', 'v', 'i', 'c', 'e', 0,
    'f', 'o', 'r', 'm', 'a', 't', 0,
    'v', 'a', 'l', 'u', 'e', '2', 0,
    'v', 'a', 'l', 'u', 'e', '1', 0,
    'i', 's', 'N', 'u', 'l', 'l', 0,
    'a', 'c', 't', 'i', 'o', 'n', 0,
    'c', 'o', 'l', 'u', 'm', 'n', 0,
    'o', 'f', 'f', 's', 'e', 't', 0,
    'f', 'i', 'l', 't', 'e', 'r', 0,
    'o', 'b', 'j', 'e', 'c', 't', 0,
    'p', 'a', 'r', 'e', 'n', 't', 0,
    't', 'a', 'b', 'l', 'e', 0,
    'g', 'e', 't', 'C', 'N', 0,
    'l', 'o', 'g', 'i', 'n', 0,
    's', 'e', 't', 'I', 'd', 0,
    'b', 'r', 'u', 's', 'h', 0,
    's', 'c', 'o', 'p', 'e', 0,
    'h', 'i', 'n', 't', 's', 0,
    't', 'o', 'H', 'e', 'x', 0,
    'f', 'l', 'a', 'g', 's', 0,
    'e', 'v', 'e', 'n', 't', 0,
    'm', 's', 'e', 'c', 's', 0,
    's', 't', 'a', 't', 'e', 0,
    'S', 'a', 'f', 'e', 't', 0,
    'n', 'u', 'l', 'l', 0,
    'p', 'o', 'r', 't', 0,
    'm', 'o', 'd', 'e', 0,
    'n', 'a', 'm', 'e', 0,
    'b', 'a', 's', 'e', 0,
    'f', 'i', 'l', 'l', 0,
    'f', 'r', 'o', 'm', 0,
    's', 'o', 'r', 't', 0,
    't', 'y', 'p', 'e', 0,
    'f', 'o', 'o', 0,
    'A', 'L', 'L', 0,
    'A', 'N', 'D', 0,
    'l', 'o', 'g', 0,
    'S', 'V', 'G', 0,
    'p', 'e', 'n', 0,
    'k', 'e', 'y', 0,
    'e', 'n', 'd', 0,
    'm', 'a', 'p', 0,
    'p', 'o', 's', 0,
    'O', 'R', 0,
    's', 'w', 0,
    's', 'y', 0,
    's', 'x', 0,
    't', 'o', 0,
    'i', 'd', 0,
};

void sipVH_Safet_0(sip_gilstate_t sipGILState, sipVirtErrorHandlerFunc sipErrorHandler, sipSimpleWrapper *sipPySelf, PyObject *sipMethod, SafetXmlObject *a0)
{
    PyObject *sipResObj = sipCallMethod(0, sipMethod, "D",a0,sipType_SafetXmlObject,NULL);

    sipParseResultEx(sipGILState, sipErrorHandler, sipPySelf, sipMethod, sipResObj, "Z");
}
static sipEnumTypeDef enumTypes[] = {
    {{-1, 0, 0, SIP_TYPE_ENUM, sipNameNr_SafetWorkflow__OutputFormat, {0}}, sipNameNr_OutputFormat, 7, NULL},
    {{-1, 0, 0, SIP_TYPE_ENUM, sipNameNr_SafetDocument__SignatureOperator, {0}}, sipNameNr_SignatureOperator, 4, NULL},
};


/*
 * This defines each type in this module.
 */
static sipTypeDef *typesTable[] = {
    &sipTypeDef_Safet_MainWindow.super.ctd_base,
    &sipTypeDef_Safet_ParsedSqlToData.super.ctd_base,
    &sipTypeDef_Safet_QList_0101SafetDocument.mtd_base,
    &sipTypeDef_Safet_QMap_0100QString_0100QString.mtd_base,
    &sipTypeDef_Safet_SafetDocument.super.ctd_base,
    &enumTypes[1].etd_base,
    &sipTypeDef_Safet_SafetVariable.super.ctd_base,
    &sipTypeDef_Safet_SafetWorkflow.super.ctd_base,
    &enumTypes[0].etd_base,
    &sipTypeDef_Safet_SafetXmlObject.super.ctd_base,
    &sipTypeDef_Safet_SafetYAWL.super.ctd_base,
};


/*
 * This defines the virtual handlers that this module implements and can be
 * used by other modules.
 */
static sipVirtHandlerFunc virtHandlersTable[] = {
    (sipVirtHandlerFunc)sipVH_Safet_0,
};


/* This defines the modules that this module needs to import. */
static sipImportedModuleDef importsTable[] = {
    {"PyQt4.QtCore", 1, NULL},
    {"PyQt4.QtGui", -1, NULL},
    {"PyQt4.QtSvg", -1, NULL},
    {"PyQt4.QtNetwork", -1, NULL},
    {"PyQt4.QtWebKit", -1, NULL},
    {"PyQt4.QtSql", -1, NULL},
    {"PyQt4.QtXml", -1, NULL},
    {NULL, -1, NULL}
};


/* This defines this module. */
sipExportedModuleDef sipModuleAPI_Safet = {
    0,
    SIP_API_MINOR_NR,
    sipNameNr_Safet,
    0,
    -1,
    sipStrings_Safet,
    importsTable,
    NULL,
    11,
    typesTable,
    NULL,
    0,
    NULL,
    0,
    NULL,
    virtHandlersTable,
    NULL,
    NULL,
    {NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL},
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL
};


/* The SIP API and the APIs of any imported modules. */
const sipAPIDef *sipAPI_Safet;
const sipExportedModuleDef *sipModuleAPI_Safet_QtCore;
const sipExportedModuleDef *sipModuleAPI_Safet_QtGui;
const sipExportedModuleDef *sipModuleAPI_Safet_QtSvg;
const sipExportedModuleDef *sipModuleAPI_Safet_QtNetwork;
const sipExportedModuleDef *sipModuleAPI_Safet_QtWebKit;
const sipExportedModuleDef *sipModuleAPI_Safet_QtSql;
const sipExportedModuleDef *sipModuleAPI_Safet_QtXml;

sip_qt_metaobject_func sip_Safet_qt_metaobject;
sip_qt_metacall_func sip_Safet_qt_metacall;
sip_qt_metacast_func sip_Safet_qt_metacast;


/* The Python module initialisation function. */
#if PY_MAJOR_VERSION >= 3
#define SIP_MODULE_ENTRY        PyInit_Safet
#define SIP_MODULE_TYPE         PyObject *
#define SIP_MODULE_DISCARD(r)   Py_DECREF(r)
#define SIP_MODULE_RETURN(r)    return (r)
#else
#define SIP_MODULE_ENTRY        initSafet
#define SIP_MODULE_TYPE         void
#define SIP_MODULE_DISCARD(r)
#define SIP_MODULE_RETURN(r)    return
#endif

#if defined(SIP_STATIC_MODULE)
extern "C" SIP_MODULE_TYPE SIP_MODULE_ENTRY()
#else
PyMODINIT_FUNC SIP_MODULE_ENTRY()
#endif
{
    static PyMethodDef sip_methods[] = {
        {0, 0, 0, 0}
    };

#if PY_MAJOR_VERSION >= 3
    static PyModuleDef sip_module_def = {
        PyModuleDef_HEAD_INIT,
        "Safet",
        NULL,
        -1,
        sip_methods,
        NULL,
        NULL,
        NULL,
        NULL
    };
#endif

    PyObject *sipModule, *sipModuleDict;
    PyObject *sip_sipmod, *sip_capiobj;

    /* Initialise the module and get it's dictionary. */
#if PY_MAJOR_VERSION >= 3
    sipModule = PyModule_Create(&sip_module_def);
#elif PY_VERSION_HEX >= 0x02050000
    sipModule = Py_InitModule(sipName_Safet, sip_methods);
#else
    sipModule = Py_InitModule(const_cast<char *>(sipName_Safet), sip_methods);
#endif

    if (sipModule == NULL)
        SIP_MODULE_RETURN(NULL);

    sipModuleDict = PyModule_GetDict(sipModule);

    /* Get the SIP module's API. */
#if PY_VERSION_HEX >= 0x02050000
    sip_sipmod = PyImport_ImportModule(SIP_MODULE_NAME);
#else
    sip_sipmod = PyImport_ImportModule(const_cast<char *>(SIP_MODULE_NAME));
#endif

    if (sip_sipmod == NULL)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(NULL);
    }

    sip_capiobj = PyDict_GetItemString(PyModule_GetDict(sip_sipmod), "_C_API");
    Py_DECREF(sip_sipmod);

#if defined(SIP_USE_PYCAPSULE)
    if (sip_capiobj == NULL || !PyCapsule_CheckExact(sip_capiobj))
#else
    if (sip_capiobj == NULL || !PyCObject_Check(sip_capiobj))
#endif
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(NULL);
    }

#if defined(SIP_USE_PYCAPSULE)
    sipAPI_Safet = reinterpret_cast<const sipAPIDef *>(PyCapsule_GetPointer(sip_capiobj, SIP_MODULE_NAME "._C_API"));
#else
    sipAPI_Safet = reinterpret_cast<const sipAPIDef *>(PyCObject_AsVoidPtr(sip_capiobj));
#endif

#if defined(SIP_USE_PYCAPSULE)
    if (sipAPI_Safet == NULL)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(NULL);
    }
#endif

    /* Export the module and publish it's API. */
    if (sipExportModule(&sipModuleAPI_Safet,SIP_API_MAJOR_NR,SIP_API_MINOR_NR,0) < 0)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(0);
    }

    sip_Safet_qt_metaobject = (sip_qt_metaobject_func)sipImportSymbol("qtcore_qt_metaobject");
    sip_Safet_qt_metacall = (sip_qt_metacall_func)sipImportSymbol("qtcore_qt_metacall");
    sip_Safet_qt_metacast = (sip_qt_metacast_func)sipImportSymbol("qtcore_qt_metacast");

    if (!sip_Safet_qt_metacast)
        Py_FatalError("Unable to import qtcore_qt_metacast");

    /* Initialise the module now all its dependencies have been set up. */
    if (sipInitModule(&sipModuleAPI_Safet,sipModuleDict) < 0)
    {
        SIP_MODULE_DISCARD(sipModule);
        SIP_MODULE_RETURN(0);
    }

    /* Get the APIs of the modules that this one is dependent on. */
    sipModuleAPI_Safet_QtCore = sipModuleAPI_Safet.em_imports[0].im_module;
    sipModuleAPI_Safet_QtGui = sipModuleAPI_Safet.em_imports[1].im_module;
    sipModuleAPI_Safet_QtSvg = sipModuleAPI_Safet.em_imports[2].im_module;
    sipModuleAPI_Safet_QtNetwork = sipModuleAPI_Safet.em_imports[3].im_module;
    sipModuleAPI_Safet_QtWebKit = sipModuleAPI_Safet.em_imports[4].im_module;
    sipModuleAPI_Safet_QtSql = sipModuleAPI_Safet.em_imports[5].im_module;
    sipModuleAPI_Safet_QtXml = sipModuleAPI_Safet.em_imports[6].im_module;

    SIP_MODULE_RETURN(sipModule);
}
